---
title: "01_Sim_data_Analysis_cvl"
author: "Yufang Wang"
date: "2025-03-18"
output: pdf_document
---

# Step 1: Set up the environment
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#G:/MasterThesis/Code/"


install_and_load <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {
      install.packages(pkg, dependencies = TRUE)
    }
    library(pkg, character.only = TRUE) }
  
}

# List of required packages
required_packages <- c("rstan", "MASS", "rstantools", "coda", "readr", "survival", "splines2", "dplyr", "simsurv", "Hmisc", "caret", "foreach", "loo")
# Install and/or load packages
install_and_load(required_packages)

source("./function_file/Functions.R")
source("./function_file/stan_constructor.R")
```


# Step 2: Generate simulated data
```{r, echo=TRUE}
set.seed(123)
n_samples <- 200
n_features <- 10 

# function for one simulation
simulation_bayint_survival <- function(criteria = c("DesignCoefficients", "baseline", "variableSelection"), n_samples = n_samples, n_features = n_features){
  
  output = list()
  
  simulated_data <- DataGenerator(n_samples = n_samples, n_features = n_features)
  dataset <- simulated_data$dataset
  Beta <- simulated_data$Beta
  output$Beta_true = Beta
  output$NumTied = length(dataset$obstime) - length(unique(dataset$obstime))
  print(output$NumTied)
  
  # Apply censoring to achieve desired event proportion
  n_events <- round(0.75 * n_samples)
  event_ids <- sample(dataset$id, size = n_events)
  dataset$status <- ifelse(dataset$id %in% event_ids, 1, 0)
  
  # Adjust observed times for censored individuals
  dataset$obstime <- ifelse(dataset$status == 0, runif(sum(dataset$status == 0), 0, dataset$eventtime),
                               dataset$eventtime)
  dataset <- dataset[, !(names(dataset) %in% c("eventtime"))]
  
  output$NumTied = length(dataset$obstime) - length(unique(dataset$obstime))
  print(output$NumTied)
  
  #constructor data for the model
  training_dataset = dataset
  testing_dataset = NULL
  
  
  stan_data_noBSpline <- stan_data_Constructer_noBSpline(
    training_dataset = training_dataset,
    testing_dataset = testing_dataset,
    log_lik_saving = TRUE
  )
  
  stan_data_bSplines <- stan_data_Constructer_BSpline(
    training_dataset = training_dataset,
    testing_dataset = testing_dataset,
    obs_window = 5,
    log_lik_saving = TRUE
  )
    
  #fit model
  model_fit_exponential <-  Bayesian_Survival_model(stan_data = stan_data_noBSpline, withPrediction = FALSE, baseline_modelling = "exponential", shrinkage = TRUE, log_likSaving = TRUE)
  model_fit_weibull <- Bayesian_Survival_model(stan_data = stan_data_noBSpline, withPrediction = FALSE, baseline_modelling = "weibull", shrinkage = TRUE, log_likSaving = TRUE)
  model_fit_bSplines <- Bayesian_Survival_model(stan_data = stan_data_bSplines, baseline_modelling = "bSplines", shrinkage = TRUE, withPrediction = FALSE, log_likSaving = TRUE)
  
  #collect diagnostics
  output$diagnostics_exponential <- summary(model_fit_exponential)$summary[, c("Rhat", "n_eff")]
  output$diagnostics_weibull <- summary(model_fit_weibull)$summary[, c("Rhat", "n_eff")]
  output$diagnostics_bSplines <- summary(model_fit_bSplines)$summary[, c("Rhat", "n_eff")]
  

  #extract the cvl from the model
  output$cvl_exponential <- cross_validated_log_likelihood (model_fit_exponential, n_samples)
  output$cvl_weibull <- cross_validated_log_likelihood (model_fit_weibull, n_samples)
  output$cvl_bSplines <- cross_validated_log_likelihood (model_fit_bSplines, n_samples)
  
  output$l_exponential <- max_log_likelihood (model_fit_exponential, n_samples)
  output$l_weibull <- max_log_likelihood (model_fit_weibull, n_samples)
  output$l_bSplines <- max_log_likelihood (model_fit_bSplines, n_samples)
  
 
  return(output)
}

replicate_times = 2
simulated_results <- replicate(replicate_times, simulation_bayint_survival(n_samples = n_samples, n_features = n_features), simplify = "array")
save.image(file = "./Data/sim_50_para_int_cvl.RData")
```

```{r, echo=TRUE}
# load(file = "./Data/sim_50_para_int.RData")
cvl_exponential <- rep(NA, replicate_times)
cvl_weibull <- rep(NA, replicate_times)
cvl_bSplines <- rep(NA, replicate_times)

l_exponential <- rep(NA, replicate_times)
l_weibull <- rep(NA, replicate_times)
l_bSplines <- rep(NA, replicate_times)

d_exponential <- rep(NA, replicate_times)
d_weibull <- rep(NA, replicate_times)
d_bSplines <- rep(NA, replicate_times)


for (i in 1:replicate_times){
  # Beta
  cvl_exponential[i] <- simulated_results[,i]$cvl_exponential
  cvl_weibull[i] <- simulated_results[,i]$cvl_weibull
  cvl_bSplines[i] <- simulated_results[,i]$cvl_bSplines
  
  l_exponential[i] <- simulated_results[,i]$l_exponential
  l_weibull[i] <- simulated_results[,i]$l_weibull
  l_bSplines[i] <- simulated_results[,i]$l_bSplines
  
  d_exponential[i] <- simulated_results[,i]$cvl_exponential - simulated_results[,i]$l_exponential
  d_weibull[i] <- simulated_results[,i]$cvl_weibull - simulated_results[,i]$l_weibull
  d_bSplines[i] <- simulated_results[,i]$cvl_bSplines - simulated_results[,i]$l_bSplines
  
  }





# Subfigure 4 Type I error
# Create side-by-side boxplots for FDR
cvl_list = list(cvl_exponential = cvl_exponential, cvl_weibull = cvl_weibull, cvl_bSplines = cvl_bSplines)
boxplot(cvl_list, names = c("Exponential", "Weibull", "B-Splines"), col = c("blue", "green", "orange"), main = "cvl Boxplots", xlab = "", ylab = "cvl")

# Subfigure 5 Type II error
l_list = list(cvl_exponential = cvl_exponential, cvl_weibull = cvl_weibull, cvl_bSplines = cvl_bSplines)
boxplot(FDR_list, names = c("Exponential", "Weibull", "B-Splines"), col = c("blue", "green", "orange"), main = "cvl Boxplots", xlab = "", ylab = "cvl", ylim = c(0, 1))
abline(h = 0.05, col = "red", lty = 2)

# Subfigure 6 Correlation for linear predictors
cor_list = list(exponential = cor_exponential, weibull = cor_weibull, bSplines = cor_bSplines, PH = cor_PH)
boxplot(cor_list, names = c("Exponential", "Weibull", "B-Splines", "ParticalLiklihood"), col = c("blue", "green", "orange", "purple"), main = "True vs. predicted linear predictor", xlab = "", ylab = "correlation", ylim = c(0, 1))

# # Subfigure 7 C index
CI_index_list = list(CI_index_exponential = CI_index_exponential, CI_index_weibull = CI_index_weibull, CI_index_bSplines = CI_index_bSplines, CI_index_PH = CI_index_PH)
boxplot(CI_index_list, names = c("Exponential", "Weibull", "B-Splines", "ParticalLiklihood"), col = c("blue", "green", "orange", "purple"), main = "C index Boxplots", xlab = "", ylab = "C index", ylim = c(0, 1))
abline(h = 0.5, col = "red", lty = 2)
```

# Step 3: visualize the estimated basline hazard
```{r, echo=TRUE}
for (i in 1:replicate_times) {
  baseline_true <- simulated_results[, i]$baseline_true 
  baseline_exponential <- simulated_results[, i]$baseline_exponential
  baseline_weibull <- simulated_results[, i]$baseline_weibull
  baseline_bSplines <- simulated_results[, i]$baseline_bSplines
  
  plot(baseline_true, col = "red", type = "l", pch = 16, lty = 1, lwd = 2)
  lines(baseline_weibull, col = "green", type = "l", pch = 16, lty = 1, lwd = 2)
  lines(baseline_exponential, col = "blue", pch = 16, lty = 1, lwd = 2)
  lines(baseline_bSplines, col = "orange", pch = 16, lty = 1, lwd = 2)
  # Add legend
  legend(
    "topleft",
    legend = c("True", "Exponential", "Weibull", "B-Splines"),
    col = c("red", "blue", "green", "orange"),
    pch = 16,
    lty = 1
  )
}

```



