---
title: "02_Sim_dataAnalysis_shrinkagewn"
author: "Yufang Wang"
date: "2025-03-18"
output: pdf_document
---

# Step 1: Set up the environment
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#G:/MasterThesis/Code/"
install_and_load <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {
      install.packages(pkg, dependencies = TRUE)
    }
    library(pkg, character.only = TRUE) }
  
}

# List of required packages
required_packages <- c("rstan", "MASS", "rstantools", "coda", "readr", "survival", "splines2", "dplyr", "simsurv", "Hmisc", "caret", "rbenchmark")
# Install and/or load packages
install_and_load(required_packages)

source("./function_file/Functions.R")
source("./function_file/stan_constructor.R")
```


# Step 2: Generate simulated data
```{r, echo=TRUE}
set.seed(123)
n_samples <- 300
n_features <- 10 

# function for one simulation
simulation_bayint_survival_shrinkage <- function(criteria = c("DesignCoefficients", "baseline", "variableSelection", "Prediction_SurvivalProb"), withPrediction = TRUE){
  
  output = list()
  
  simulated_data <- DataGenerator(n_samples = n_samples, n_features = 10)
  dataset <- simulated_data$dataset
  Beta <- simulated_data$Beta
  output$Beta_true = Beta
  
  #constructor data for the model
  #constructor data for the model
  if (withPrediction) {
    samples <- sample(1:nrow(dataset), 100)
    training_dataset <- dataset[-samples, ]
    testing_dataset <- dataset[samples, ]
  } else{
    training_dataset = dataset
    testing_dataset = NULL
  }
  stan_data_PH <- stan_data_Constructer_PH(
    training_dataset = training_dataset,
    testing_dataset = testing_dataset
  )
  
  
  stan_data_bSplines <- stan_data_Constructer_BSpline(
    training_dataset = training_dataset,
    testing_dataset = testing_dataset,
    obs_window = 5
  )
    
  #fit model
  model_fit_bSplines_withShrinkage <- Bayesian_Survival_model(stan_data = stan_data_bSplines, baseline_modelling = "bSplines", shrinkage = TRUE)
  model_fit_bSplines_noShrinkage <- Bayesian_Survival_model(stan_data = stan_data_bSplines, baseline_modelling = "bSplines", shrinkage = FALSE)
  
  model_fit_PH_withShrinkage <- Bayesian_Survival_model(stan_data = stan_data_PH, baseline_modelling = "none", shrinkage = TRUE)
  model_fit_PH_noShrinkage <- Bayesian_Survival_model(stan_data = stan_data_PH, baseline_modelling = "none", shrinkage = FALSE)
  
  #collect diagnostics
  output$diagnostics_bSplines_withShrinkage <- summary(model_fit_bSplines_withShrinkage)$summary[, c("Rhat", "n_eff")]
  output$diagnostics_bSplines_noShrinkage <- summary(model_fit_bSplines_noShrinkage)$summary[, c("Rhat", "n_eff")]
  
  output$diagnostics_PH_withShrinkage <- summary(model_fit_PH_withShrinkage)$summary[, c("Rhat", "n_eff")]
  output$diagnostics_PH_noShrinkage <- summary(model_fit_PH_noShrinkage)$summary[, c("Rhat", "n_eff")]

  #extract the info from the bayesian model fit
  model_result_bSplines_withShrinkage <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_bSplines_withShrinkage, model_type = "bSplines", criteria = criteria)
  model_result_bSplines_noShrinkage <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_bSplines_noShrinkage, model_type = "bSplines", criteria = criteria)
  
  model_result_PH_withShrinkage <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_PH_withShrinkage, model_type = "none", criteria = criteria)
  model_result_PH_noShrinkage <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_PH_noShrinkage, model_type = "none", criteria = criteria)
  
  
  #---------coefficients for X----------
  if ("DesignCoefficients" %in% criteria){
    output$Beta_est_bSplines_withShrinkage = model_result_bSplines_withShrinkage$Beta_bayesian_est[, "mean"]
    output$Beta_est_bSplines_noShrinkage = model_result_bSplines_noShrinkage$Beta_bayesian_est[, "mean"]
    
    output$Beta_est_PH_withShrinkage = model_result_PH_withShrinkage$Beta_bayesian_est[, "mean"]
    output$Beta_est_PH_noShrinkage = model_result_PH_noShrinkage$Beta_bayesian_est[, "mean"]
  }
  
  #----------baseline hazard----------
  # Transfer the param into baseline 
  # hazard function regarding t
  #-----------------------------------
  
  if ("baseline" %in% criteria) {
    if (withPrediction){
      output$time_vec <-
      sort(training_dataset[training_dataset$status == 1, ]$obstime) # obs_window = 5
    } else {
       output$time_vec <-
      sort(dataset[dataset$status == 1, ]$obstime) # obs_window = 5
    }
   
    output$baseline_true <-  10 * 2 * (output$time_vec ** (10 - 1))
    
    output$baseline_bSplines_withShrinkage <-
      exp(as.matrix(stan_data_bSplines$basis) %*% as.matrix(model_result_bSplines_withShrinkage$baselinePara[, "mean"]))
    
    output$baseline_bSplines_noShrinkage <-
      exp(as.matrix(stan_data_bSplines$basis) %*% as.matrix(model_result_bSplines_noShrinkage$baselinePara[, "mean"]))
  }
  
  
  if ("variableSelection" %in% criteria) {
    output$variableSelection_bSplines_withShrinkage <-
      model_result_bSplines_withShrinkage$variableSelection
    
    output$variableSelection_bSplines_noShrinkage <-
      model_result_bSplines_noShrinkage$variableSelection
    
    output$variableSelection_PH_withShrinkage <-
      model_result_PH_withShrinkage$variableSelection
    
    output$variableSelection_PH_noShrinkage <-
      model_result_PH_noShrinkage$variableSelection
  }
  
  if ("Prediction_SurvivalProb" %in% criteria) {
    output$time = testing_dataset$obstime
    output$true_status = testing_dataset$status
    
    output$eta_true = as.vector(as.matrix(stan_data_bSplines$x_new) %*% output$Beta_true[1:10] + as.matrix(stan_data_bSplines$x_int_new) %*% output$Beta_true[11:55])
    

    output$eta_pred_bSplines_withShrinkage = model_result_bSplines_withShrinkage$eta_pred
    output$eta_pred_bSplines_noShrinkage = model_result_bSplines_noShrinkage$eta_pred

    
    output$eta_pred_PH_withShrinkage = model_result_PH_withShrinkage$eta_pred
    output$eta_pred_PH_noShrinkage = model_result_PH_noShrinkage$eta_pred
    rm(training_dataset, testing_dataset)
  }
  return(output)
  }


replicate_times = 2
simulated_results <- replicate(replicate_times, simulation_bayint_survival_shrinkage(), simplify = "array")
#save.image(file = "./Data/sim_50_para_shrinkagenowith_PH.RData")
```

```{r, echo=TRUE}
#load(file = "./Data/sim_50_para_shrinkagenowith_PH.RData")
Beta_est_bSplines_withShrinkag <- matrix(nrow = replicate_times, ncol = 55)
Beta_est_bSplines_noShrinkag <- matrix(nrow = replicate_times, ncol = 55)
Beta_est_PH_withShrinkage <- matrix(nrow = replicate_times, ncol = 55)
Beta_est_PH_noShrinkag <- matrix(nrow = replicate_times, ncol = 55)

# Bias  
Bias_bSplines_withShrinkag = rep(NA, ncol = 55)
Bias_bSplines_noShrinkag = rep(NA, ncol = 55)
Bias_PH_withShrinkage = rep(NA, ncol = 55)
Bias_PH_noShrinkag = rep(NA, ncol = 55)

# Variance
Variance_bSplines_withShrinkag_ = matrix(nrow = replicate_times, ncol = 55)
Variance_bSplines_noShrinkag_ = matrix(nrow = replicate_times, ncol = 55)
Variance_PH_withShrinkage_ = matrix(nrow = replicate_times, ncol = 55)
Variance_PH_noShrinkag_ = matrix(nrow = replicate_times, ncol = 55)

# MSE
MSEs_bSplines_withShrinkag_ = matrix(nrow = replicate_times, ncol = 55)
MSEs_bSplines_noShrinkag_ = matrix(nrow = replicate_times, ncol = 55)
MSEs_PH_withShrinkage_ = matrix(nrow = replicate_times, ncol = 55)
MSEs_PH_noShrinkag_ = matrix(nrow = replicate_times, ncol = 55)

# Type I error
FDR_bSplines_withShrinkag = rep(NA, replicate_times)
FDR_bSplines_noShrinkag = rep(NA, replicate_times)
FDR_PH_withShrinkage = rep(NA, replicate_times)
FDR_PH_noShrinkag = rep(NA, replicate_times)

# Type II error
Num_Selected_bSplines_withShrinkag = rep(NA, replicate_times)
Num_Selected_bSplines_noShrinkag = rep(NA, replicate_times)
Num_Selected_PH_withShrinkage = rep(NA, replicate_times)
Num_Selected_PH_noShrinkag = rep(NA, replicate_times)

# correlation, i.e., Prediction at the linear predictor level
cor_bSplines_withShrinkag = rep(NA, replicate_times)
cor_bSplines_noShrinkag = rep(NA, replicate_times)
cor_PH_withShrinkage = rep(NA, replicate_times)
cor_PH_noShrinkag = rep(NA, replicate_times)

#C INDEX, i.e., prediction at the C index level
C_index_bSplines_withShrinkag = rep(NA, replicate_times)
C_index_bSplines_noShrinkag = rep(NA, replicate_times)
C_index_PH_withShrinkage = rep(NA, replicate_times)
C_index_PH_noShrinkag = rep(NA, replicate_times)


for (i in 1:replicate_times){
  # Beta
  Beta_true <- simulated_results[,i]$Beta_true
  Bias_bSplines_withShrinkag[i, ] <- simulated_results[,i]$Beta_est_bSplines_withShrinkage
  Bias_bSplines_noShrinkag[i, ] <- simulated_results[,i]$Beta_est_bSplines_noShrinkage
  Bias_PH_withShrinkage[i, ] <- simulated_results[,i]$Beta_est_PH_withShrinkage
  Bias_PH_noShrinkag[i, ] <-  simulated_results[,i]$Beta_est_PH_noShrinkage
  
  # Variance
  Variance_bSplines_withShrinkag_[i, ] = simulated_results[,i]$Beta_est_bSplines_withShrinkage - Beta_true
  Variance_bSplines_noShrinkag_[i, ] = simulated_results[,i]$Beta_est_bSplines_noShrinkage - Beta_true
  Variance_PH_withShrinkage_[i, ] = simulated_results[,i]$Beta_est_PH_withShrinkage - Beta_true
  Variance_PH_noShrinkag_ = simulated_results[,i]$Beta_est_PH_noShrinkage - Beta_true
  
  # MSE
  MSEs_bSplines_withShrinkag_[i, ] <- (simulated_results[,i]$Beta_est_bSplines_withShrinkage - Beta_true)**2
  MSEs_bSplines_noShrinkag_[i, ] <- (simulated_results[,i]$Beta_est_bSplines_noShrinkage - Beta_true)**2
  MSEs_PH_withShrinkage_[i, ] <- (simulated_results[,i]$Beta_est_PH_withShrinkage - Beta_true)**2
  MSEs_PH_noShrinkag_[i, ] <- (simulated_results[,i]$Beta_est_PH_noShrinkage - Beta_true)**2
  
  # FDR (Type I error)
  variableSelection_reference <- ifelse(simulated_results[,i]$Beta_true != 0, TRUE, FALSE)
  
  # FDR
  variableSelection_reference <- simulated_results[, i]$Beta_true != 0
  
  Selection_bSplines_withShrinkage <- simulated_results[,i]$variableSelection_bSplines_withShrinkage
  Selection_bSplines_noShrinkage <- simulated_results[,i]$variableSelection_bSplines_noShrinkage
  Selection_PH_withShrinkage <- simulated_results[,i]$variableSelection_PH_withShrinkage
  Selection_PH_noShrinkage <- simulated_results[,i]$variableSelection_PH_noShrinkage
  

  FDR_bSplines_withShrinkag[i] <- sum(Selection_exponential & !variableSelection_reference) / sum(Selection_exponential)
  FDR_bSplines_noShrinkag[i] <- sum(Selection_weibull & !variableSelection_reference) / sum(Selection_weibull)
  FDR_PH_withShrinkage[i] <- sum(Selection_bSplines & !variableSelection_reference) / sum(Selection_bSplines)
  FDR_PH_noShrinkag[i] <- sum(Selection_PH & !variableSelection_reference) / sum(Selection_PH)
  
  # Number of selected variables (Type II error)
  Num_Selected_bSplines_withShrinkag[i] = sum(Selection_bSplines_withShrinkage)
  Num_Selected_bSplines_noShrinkag[i] = sum(Selection_bSplines_noShrinkage)
  Num_Selected_PH_withShrinkage[i] = sum(Selection_PH_withShrinkage)
  Num_Selected_PH_noShrinkag[i] = sum(Selection_PH_noShrinkage)

  
  #linear predictor
  eta_true <- simulated_results[,i]$eta_true
  eta_pre_bSplines_withShrinkage <- simulated_results[, i]$eta_pred_bSplines_withShrinkage
  eta_pre_bSplines_noShrinkage <- simulated_results[, i]$eta_pred_bSplines_noShrinkage
  eta_pre_PH_withShrinkage <- simulated_results[, i]$eta_pred_PH_withShrinkage
  eta_pre_PH_noShrinkage <- simulated_results[, i]$eta_pred_PH_noShrinkage
  
  cor_bSplines_withShrinkag[i] <- cor(eta_true, eta_pre_bSplines_withShrinkage)
  cor_bSplines_noShrinkag[i] <- cor(eta_true, eta_pre_bSplines_noShrinkage)
  cor_PH_withShrinkage[i] <- cor(eta_true, eta_pre_PH_withShrinkage)
  cor_PH_noShrinkag[i] <- cor(eta_true, eta_pre_PH_noShrinkage)
  
  # CI 
  time <- simulated_results[,i]$time
  true_status <- simulated_results[,i]$true_status
  sp_true <- exp(-2 * time^10 * exp(eta_true))
  
  C_index_bSplines_withShrinkag[i] <- rcorr.cens(-eta_pre_bSplines_withShrinkage, Surv(time, true_status))["C Index"] # rcorr.cens
  C_index_bSplines_noShrinkag[i] <- rcorr.cens(-eta_pre_bSplines_noShrinkage, Surv(time, true_status))["C Index"]
  C_index_PH_withShrinkage[i] <- rcorr.cens(-eta_pre_PH_withShrinkage, Surv(time, true_status))["C Index"]
  C_index_PH_noShrinkag[i] <- rcorr.cens(-eta_pre_PH_noShrinkage, Surv(time, true_status))["C Index"]
  
}

# Bias
Beta_est_bSplines_withShrinkag <- matrix(nrow = replicate_times, ncol = 55)
Beta_est_bSplines_noShrinkag <- matrix(nrow = replicate_times, ncol = 55)
Beta_est_PH_withShrinkage <- matrix(nrow = replicate_times, ncol = 55)
Beta_est_PH_noShrinkag <- matrix(nrow = replicate_times, ncol = 55)

Bias_bSplines_withShrinkag = apply(Beta_est_bSplines_withShrinkag, 2, mean) - Beta_true
Bias_bSplines_noShrinkag = apply(Beta_est_bSplines_noShrinkag, 2, mean) - Beta_true
Bias_PH_withShrinkage = apply(Beta_est_PH_withShrinkage, 2, mean) - Beta_true
Bias_PH_noShrinkag = apply(Beta_est_PH_noShrinkag, 2, mean) - Beta_true

# Variance 
Variance_bSplines_withShrinkag = apply(Variance_bSplines_withShrinkag_, 2, var)
Variance_bSplines_noShrinkag = apply(Variance_bSplines_noShrinkag_, 2, var)
Variance_PH_withShrinkage = apply(Variance_PH_withShrinkage_, 2, var)
Variance_PH_noShrinkag = apply(Variance_PH_noShrinkag_, 2, var)

# MSE
MSEs_bSplines_withShrinkag <- apply(MSEs_bSplines_withShrinkag_, 2, mean)
MSEs_bSplines_noShrinkag <- apply(MSEs_bSplines_noShrinkag_, 2, mean)
MSEs_PH_withShrinkage <- apply(MSEs_PH_withShrinkage_, 2, mean)
MSEs_PH_noShrinkag <- apply(MSEs_PH_noShrinkag_, 2, mean)

# visualized result
fill_vector = (Beta_true != 0)

par(mfrow = c(3, 3))

# Subfigure 1: Bias
plot(Bias_bSplines_withShrinkag, type = "o", col = "blue", xlab = "estimated Betas", ylab = "Bias", ylim = c(0, 0.3), main = "Bias for Beta estimation", pch = 16)

# Add background rectangles
for (i in 1:length(Beta_true)) {
  if (fill_vector[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}


lines(Bias_bSplines_noShrinkag, type = "o", col = "green", pch = 16)
lines(Bias_PH_withShrinkage, type = "o", col = "orange", pch = 16)
lines(Bias_bSplines_withShrinkag, type = "o", col = "blue", pch = 16)
lines(Bias_PH_noShrinkag, type = "o", col = "grey", pch = 16)

abline(v = 10, col = "red", lty = 2)
legend("topright", legend = c("bSplines_withShrinkag", "bSplines_noShrinkag", "PL_withShrinkage", "PL_noShrinkag"), col = c("blue", "green", "orange", "grey"), pch = 16, lty = 1) # Add legend

# Subfigure 2: Variance
plot(Variance_bSplines_withShrinkag, type = "o", col = "blue", xlab = "estimated Betas", ylab = "Variance", ylim = c(0, 0.3), main = "Variance for Beta estimation", pch = 16)

# Add background rectangles
for (i in 1:length(Beta_true)) {
  if (fill_vector[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}

lines(Variance_bSplines_noShrinkag, type = "o", col = "green", pch = 16)
lines(Variance_PH_withShrinkage, type = "o", col = "orange", pch = 16)
lines(Variance_bSplines_withShrinkag, type = "o", col = "blue", pch = 16)
lines(Variance_PH_noShrinkag, type = "o", col = "grey", pch = 16)

abline(v = 10, col = "red", lty = 2)
abline(h = 0, col = "red", lty = 2)
legend("topright", legend = c("bSplines_withShrinkag", "bSplines_noShrinkag", "PL_withShrinkage", "PL_noShrinkag"), col = c("blue", "green", "orange", "grey"), pch = 16, lty = 1) # Add legend

# Subfigure 3: MSE
plot(MSEs_bSplines_withShrinkag, type = "o", col = "blue", xlab = "estimated Betas", ylab = "MSE", ylim = c(0, 0.3), main = "MSE for Beta estimation", pch = 16)

# Add background rectangles
for (i in 1:length(Beta_true)) {
  if (fill_vector[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}

lines(MSEs_bSplines_noShrinkag, type = "o", col = "green", pch = 16)
lines(MSEs_PH_withShrinkage, type = "o", col = "orange", pch = 16)
lines(MSEs_bSplines_withShrinkag, type = "o", col = "blue", pch = 16)
lines(MSEs_PH_noShrinkag, type = "o", col = "grey", pch = 16)

abline(v = 10, col = "red", lty = 2)
legend("topright", legend = c("bSplines_withShrinkag", "bSplines_noShrinkag", "PL_withShrinkage", "PL_noShrinkag"), col = c("blue", "green", "orange", "grey"), pch = 16, lty = 1) # Add legend


# Subfigure 4 Type I error
# Create side-by-side boxplots for FDR
FDR_list = list(bSplines_withShrinkag = FDR_bSplines_withShrinkag, bSplines_noShrinkag = FDR_bSplines_noShrinkag, PL_withShrinkage = FDR_PH_withShrinkage, PL_noShrinkag = FDR_PH_noShrinkag)
boxplot(FDR_list, names = c("bSplines_withShrinkag", "bSplines_noShrinkag", "PL_withShrinkage", "PL_noShrinkag"), col = c("blue", "green", "orange", "grey"), main = "FDR Boxplots", xlab = "", ylab = "FDR")

# Subfigure 5 Type II error
Num_Selected_list = list(bSplines_withShrinkag = Num_Selected_bSplines_withShrinkag, bSplines_noShrinkag = Num_Selected_bSplines_noShrinkag, PL_withShrinkage = Num_Selected_PH_withShrinkage, PL_noShrinkag = Num_Selected_PH_noShrinkag)
boxplot(Num_Selected_list, names = c("bSplines_withShrinkag", "bSplines_noShrinkag", "PL_withShrinkage", "PL_noShrinkag"), col = c("blue", "green", "orange", "grey"), main = "FDR Boxplots", xlab = "", ylab = "FDR")

# Subfigure 6 Correlation for linear predictors
cor_list = list(bSplines_withShrinkag = cor_bSplines_withShrinkag, bSplines_noShrinkag = cor_bSplines_noShrinkag, PL_withShrinkage = cor_PH_withShrinkage, PL_noShrinkag = cor_PH_noShrinkag)
boxplot(cor_list, names = c("bSplines_withShrinkag", "bSplines_noShrinkag", "PL_withShrinkage", "PL_noShrinkag"), col = c("blue", "green", "orange", "grey"), main = "True vs. predicted linear predictor", xlab = "", ylab = "correlation")

# # Subfigure 7 C index
C_index_list = list(bSplines_withShrinkag = C_index_bSplines_withShrinkag, bSplines_noShrinkag = C_index_bSplines_noShrinkag, PL_withShrinkage = C_index_PH_withShrinkage, PL_noShrinkag = C_index_PH_noShrinkag)
boxplot(C_index_list, names = c("bSplines_withShrinkag", "bSplines_noShrinkag", "PL_withShrinkage", "PL_noShrinkag"), col = c("blue", "green", "orange", "grey"), main = "C index Boxplots", xlab = "", ylab = "C index")
```

# Step 3: Furture check bias-variance
```{r, echo=TRUE}
#load(file = "./Data/sim_50_para_shrinkagenowith_PH.RData")

# Ground-truth info
Beta_true = rep(NA, 55)
LinearPred_true = matrix(nrow = replicate_times, ncol = 100)

# Output of bSplines with vs. no shrinkage for betas
Beta_bSpline_noShrinkage = matrix(nrow = replicate_times, ncol = 55)
Beta_bSpline_withShrinkage =  matrix(nrow = replicate_times, ncol = 55)

LinearPred_bSpline_noShrinkage = matrix(nrow = replicate_times, ncol = 100)
LinearPred_bSpline_withShrinkage = matrix(nrow = replicate_times, ncol = 100)

#Output of partical likelihood with vs. no shrinkage for betas
Beta_PH_noShrinkage = matrix(nrow = replicate_times, ncol = 55)
Beta_PH_withShrinkage =  matrix(nrow = replicate_times, ncol = 55)

LinearPred_PH_noShrinkage = matrix(nrow = replicate_times, ncol = 100)
LinearPred_PH_withShrinkage = matrix(nrow = replicate_times, ncol = 100)



# FDR
variableSelection_reference = rep(NA, 55)
Selection_bSplines_withShrinkage = matrix(nrow = replicate_times, ncol = 55)
Selection_bSplines_noShrinkage = matrix(nrow = replicate_times, ncol = 55)

Selection_PH_withShrinkage = matrix(nrow = replicate_times, ncol = 55)
Selection_PH_noShrinkage = matrix(nrow = replicate_times, ncol = 55)



for (i in 1:replicate_times){
  # Ground-truth info 
  Beta_true <- simulated_results[,i]$Beta_true
  
  Beta_bSpline_withShrinkage[i, ] <-  simulated_results[,i]$Beta_est_bSplines_withShrinkage
  Beta_bSpline_noShrinkage[i, ] <-  simulated_results[,i]$Beta_est_bSplines_noShrinkage
  
  
  Beta_PH_withShrinkage[i,] <-  simulated_results[,i]$Beta_est_PH_withShrinkage
  Beta_PH_noShrinkage[i, ] <-  simulated_results[,i]$Beta_est_PH_noShrinkage
  
  
  # Linear predictor
  LinearPred_true[i, ] <- simulated_results[,i]$eta_true
  LinearPred_bSpline_withShrinkage[i, ] <- simulated_results[,i]$eta_pred_bSplines_withShrinkage
  LinearPred_bSpline_noShrinkage[i, ] <- simulated_results[,i]$eta_pred_bSplines_noShrinkage
  
  LinearPred_PH_withShrinkage[i, ] <- simulated_results[,i]$eta_pred_PH_withShrinkage
  LinearPred_PH_noShrinkage[i, ] <- simulated_results[,i]$eta_pred_PH_noShrinkage
  
  
  # FDR
  variableSelection_reference <- ifelse(simulated_results[,i]$Beta_true != 0, TRUE, FALSE)
  
  Selection_bSplines_withShrinkage[i, ] <- simulated_results[,i]$variableSelection_bSplines_withShrinkage
  Selection_bSplines_noShrinkage[i, ] <- simulated_results[,i]$variableSelection_bSplines_noShrinkage

  Selection_PH_withShrinkage[i, ] <- simulated_results[,i]$variableSelection_PH_withShrinkage
  Selection_PH_noShrinkage[i, ] <- simulated_results[,i]$variableSelection_PH_noShrinkage
}


par(mfrow = c(2, 2))
Bias_bSpline_withShrinkage <- apply(Beta_bSpline_withShrinkage, 2, mean) - Beta_true
Bias_bSpline_noShrinkage <- apply(Beta_bSpline_noShrinkage, 2, mean) - Beta_true
plot(Bias_bSpline_noShrinkage, Bias_bSpline_withShrinkage,
     xlab = "Bias (No Shrinkage)", ylab = "Bias (With Shrinkage)",
     main = "Bias Comparison: No Shrinkage vs With Shrinkage")
abline(0, 1, col = "red", lty = 2)  # y = x line


var_bSpline_withShrinkage <- apply(Beta_bSpline_withShrinkage - apply(Beta_bSpline_withShrinkage, 2, mean), 2, function(x){mean(x^2)})
Var_bSpline_noShrinkage <- apply(Beta_bSpline_noShrinkage - apply(Beta_bSpline_noShrinkage, 2, mean), 2, function(x){mean(x^2)})
plot(Var_bSpline_noShrinkage, var_bSpline_withShrinkage,
     xlab = "Variance (No Shrinkage)", ylab = "Variance (With Shrinkage)",
     main = "Variance Comparison: No Shrinkage vs With Shrinkage")
abline(0, 1, col = "red", lty = 2)  # y = x line

# visualized result
fill_vector = (simulated_results[, 1]$Beta_true != 0)

plot(apply(Selection_bSplines_withShrinkage, 2, mean), type = "o", col = "blue", xlab = "estimated Betas", ylab = "FDR", ylim = c(0, 1), main = "FDR for Beta estimation", pch = 16)

# Add background rectangles
for (i in 1:length(variableSelection_reference)) {
  if (fill_vector[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}

lines(apply(Selection_bSplines_withShrinkage, 2, mean), type = "o", col = "blue", pch = 16)
lines(apply(Selection_bSplines_noShrinkage, 2, mean), type = "o", col = "green", pch = 16)
lines(apply(Selection_PH_withShrinkage, 2, mean), type = "o", col = "orange", pch = 16)
lines(apply(Selection_PH_noShrinkage, 2, mean), type = "o", col = "grey", pch = 16)
# Add legend
legend("topright", legend = c("B_withshrinkage", "B_noshrinkage", "PH_withshrinkage", "PH_noshrinkage"), col = c("blue", "green", "orange", "grey"), pch = 16, lty = 1)
```

# Tracking time
```{r, echo=TRUE}
set.seed(123)
n_samples <- 300
n_features <- 10 
simulated_data <- DataGenerator(n_samples = n_samples, n_features = 10)
samples <- sample(1:nrow(dataset), 100)
training_dataset <- dataset[-samples, ]
testing_dataset <- dataset[samples, ]

stan_data_PH <- stan_data_Constructer_PH(
    training_dataset = training_dataset,
    testing_dataset = testing_dataset)

stan_data_bSplines <- stan_data_Constructer_BSpline(
    training_dataset = training_dataset,
    testing_dataset = testing_dataset,
    obs_window = 5
  )

t_eval = benchmark(
  "bSpline_shrinkage" = {
     model_fit_withShrinkage <- Bayesian_Survival_model(stan_data = stan_data_bSplines, baseline_modelling = "bSplines", shrinkage = TRUE)
  },
  
  "PH_shrinkage" = {
     model_fit_withShrinkage <- Bayesian_Survival_model(stan_data = stan_data_PH, baseline_modelling = "none", shrinkage = TRUE)
  },
  
  replications = 50
)
t_eval

save(t.eval, file = "./Data/t_eval.RData")
```
