---
title: "03_Real_Data_Analysis"
author: "Yufang Wang"
date: "2025-03-18"
output: pdf_document
---

# Step 1: Set up the environment
```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#G:/MasterThesis/Code/"
source("./function_file/Functions.R")
source("./function_file/stan_constructor.R")

install_and_load <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {
      install.packages(pkg, dependencies = TRUE)
    }
    library(pkg, character.only = TRUE) }
  
}

# List of required packages
required_packages <- c("rstan", "MASS", "rstantools", "coda", "readr", "survival", "splines2", "dplyr", "simsurv", "Hmisc", "caret", "corrplot","ggplot2", "loo", "survival", "caret")
# Install and/or load packages
install_and_load(required_packages)
```


# Step 2: Organize and strafied the real-world data
```{r, echo=TRUE}
real_df <- readRDS("./Data/imputed_NOTR_DGF.rds")
# sum(!complete.cases(real_df))
# mean(real_df$status == "graftloss")
# mean(real_df$status == "alive")
# mean(real_df$status == "death")

# # Reversed KM for follow-up analysis
# fit <- survfit(Surv(real_df$time, real_df$status != "graftloss") ~ 1)
# plot(fit)
# abline(h = 0.5, col = "red", lty = 2)
# 
# str(real_df)
real_df <- real_df[, !names(real_df) %in% "ID"]

# set the factor variable being sum-to-zero encoded
contrasts(real_df$Recipientsex) <- contr.sum(levels(real_df$Recipientsex))
contrasts(real_df$Donorsex) <- contr.sum(levels(real_df$Donorsex))
contrasts(real_df$Smoking) <- contr.sum(levels(real_df$Smoking))
contrasts(real_df$InitialPrimaryDiseaseET_regroup) <- contr.sum(levels(real_df$InitialPrimaryDiseaseET_regroup))
contrasts(real_df$Donorcauseofdeath_group) <- contr.sum(levels(real_df$Donorcauseofdeath_group))


# center the numeric variables
real_df$Recipientage <- scale(real_df$Recipientage)
real_df$Dialysisdaysrenine <- scale(real_df$Dialysisdaysrenine)
real_df$Donorage <- scale(real_df$Donorage)
real_df$Lastcreatininemgdl <- scale(real_df$Lastcreatininemgdl)
real_df$Warm_ischaemic_period_1 <- scale(real_df$Warm_ischaemic_period_1)
real_df$Cold_ischaemic_period <- scale(real_df$Cold_ischaemic_period)
real_df$HLA_mismatch <- scale(real_df$HLA_mismatch)
real_df$DonorBMI <- scale(real_df$DonorBMI)
real_df$Recipient_BMI <- scale(real_df$Recipient_BMI)
#

# print(colnames(real_df)[factorName])

real_df <- real_df[, !(names(real_df) %in% "InitialOnmachineindicator")]
real_df$Donorcauseofdeath_group <- ifelse(real_df$Donorcauseofdeath_group == "Cardiac", "Cardiac", "Others")
real_df$Donorcauseofdeath_group <- factor(real_df$Donorcauseofdeath_group)
contrasts(real_df$Donorcauseofdeath_group) <- contr.sum(levels(real_df$Donorcauseofdeath_group))

real_df$InitialPrimaryDiseaseET_regroup <- ifelse(real_df$InitialPrimaryDiseaseET_regroup == "Diabetes Mellitus", "Diabetes", "Others")
real_df$InitialPrimaryDiseaseET_regroup <- factor(real_df$InitialPrimaryDiseaseET_regroup)
contrasts(real_df$InitialPrimaryDiseaseET_regroup) <- contr.sum(levels(real_df$InitialPrimaryDiseaseET_regroup))


strafied_Data_DBD <- subset(subset(real_df, real_df$TypecadavericDBDDCD == "DBD"), select = -c(TypecadavericDBDDCD, Warm_ischaemic_period_1))

strafied_Data_DCD <- subset(subset(real_df, real_df$TypecadavericDBDDCD == "DCD"), select = -c(TypecadavericDBDDCD))
```

# Section 1
## Step 3: EDA for strafied data DBD
```{r, echo=TRUE}
str(strafied_Data_DBD)
# Get the overall range for numeric columns
numeric_data <- strafied_Data_DBD[sapply(strafied_Data_DBD, is.numeric)]
apply(numeric_data, 2, range)

# Get the levels for factor columns
factor_data <- strafied_Data_DBD[sapply(strafied_Data_DBD, is.factor)]
lapply(factor_data, levels)

# # Reversed KM for follow-up analysis
fit <- survfit(Surv(strafied_Data_DBD$time, strafied_Data_DBD$status != "graftloss") ~ 1)
plot(fit)
abline(h = 0.5, col = "red", lty = 2)

sum(!names(strafied_Data_DBD) %in% c("time", "status"))
```
## Step 4: Verify the existence of interaction effects
```{r, echo=TRUE}
strafied_Data_DBD_int <- includingInter(strafied_Data_DBD)
strafied_Data_DBD_int <- subset(strafied_Data_DBD_int, select = -c(id))
```

```{r, echo=TRUE}
# STEP 1: 5-FOLD CROSS-VALIDATION 
set.seed(123456)
# Number of folds
k <- 5

# Assuming p is the number of coefficients
p <- 91

# Preallocate matrices/vectors
bSplines_model_Int_beta <- matrix(NA, nrow = k, ncol = p)
bSplines_model_Int_variableSelection <- matrix(NA, nrow = k, ncol = p)
bSplines_model_Int_Prediction <- vector("list", k)

PL_Int_beta <- matrix(NA, nrow = k, ncol = p)
PL_Int_variableSelection <- matrix(NA, nrow = k, ncol = p)
PL_Int_Prediction <- vector("list", k)


# Create 5-fold cross-validation indices

folds <- createFolds(strafied_Data_DBD_int$status, k = 5, list = TRUE, returnTrain = FALSE)
CI_index_PL <- rep(NA, 5)
CI_index_bSplines <- rep(NA, 5)

# Cross validation (5-fold)
for (i in seq_along(folds)){
  testing_indices <- folds[[i]]
  testing_data <- strafied_Data_DBD_int[testing_indices, ]
  training_data <- strafied_Data_DBD_int[-testing_indices,]
  
  cat("Fold", i, "\n")
  cat("Training set size:", nrow(training_data), "\n")
  cat("Test set size:", nrow(testing_data), "\n\n")

  # insert your model training and evaluation code here
  #-----------MODEL 1: bSpline model----------
  Data_DBD_bSplines_Int <- stan_data_Constructer_BSpline(
    training_dataset = training_data,
    testing_dataset = testing_data,
    obs_window = 3415,
    log_lik_saving = TRUE,
    havingInt = TRUE
  )
  bSplines_model_Int <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_Int,
                                                baseline_modelling = "bSplines",
                                                shrinkage = TRUE,
                                                withPrediction = TRUE,
                                                havingInt = TRUE)
  
  #-----------MODEL 2: PL model----------
  Data_DBD_PL_Int <- stan_data_Constructer_PL(
    training_dataset = training_data,
    testing_dataset = testing_data,
    havingInt = TRUE
  )
  
  PL_model_Int <- Bayesian_Survival_model(
    stan_data = Data_DBD_PL_Int,
    baseline_modelling = "none",
    shrinkage = TRUE,
    withPrediction = TRUE,
    havingInt = TRUE,
    niter = 10000,
    nwarmup = 2000,
    thin = 10,
    chains = 4
  )
  
  
  # Extract the model result
  bSplines_model_Int_results = Bayesian_Survival_result_Extract(
    bayesian_model_fit = bSplines_model_Int,
    model_type = "bSplines",
    criteria = c(
      "DesignCoefficients",
      "variableSelection",
      "Prediction_SurvivalProb"
    )
  )
  
  
  bSplines_model_Int_beta[i,] <-
    bSplines_model_Int_results$Beta_bayesian_est[, "mean"]
  bSplines_model_Int_variableSelection[i,] <-
    bSplines_model_Int_results$variableSelection
  bSplines_model_Int_Prediction[[i]] <-
    bSplines_model_Int_results$eta_pred
  
  PL_model_Int_results = Bayesian_Survival_result_Extract(
    bayesian_model_fit = PL_model_Int,
    model_type = "none",
    criteria = c(
      "DesignCoefficients",
      "variableSelection",
      "Prediction_SurvivalProb"
    )
  )
  
  PL_Int_beta[i,] <- PL_model_Int_results$Beta_bayesian_est[, "mean"]
  PL_Int_variableSelection[i,] <-
    PL_model_Int_results$variableSelection
  PL_Int_Prediction[[i]] <- PL_model_Int_results$eta_pred
  
  
  #c-INDEX
  a <- PL_Int_Prediction[[i]]; b <- bSplines_model_Int_Prediction[[i]]
  CI_index_PL[i] <- rcorr.cens(-a,
      Surv(testing_data$obstime, testing_data$status))["C Index"]
  CI_index_bSplines[i] <- rcorr.cens(-b,
      Surv(testing_data$obstime, testing_data$status))["C Index"]
}

cbind(mean(CI_index_PL), mean(CI_index_bSplines))
save.image(file = "./Data/03_results_DBD_Step1.RData")
```

```{r, echo=TRUE}
# STEP 2: get the Schoenfeld residuals

#---bSpline model
Data_DBD_bSplines_Int_full <- stan_data_Constructer_BSpline(
  training_dataset = strafied_Data_DBD_int,
  testing_dataset = NULL,
  obs_window = 3415,
  log_lik_saving = TRUE,
  havingInt = TRUE
)
bSplines_model_Int_full <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_Int_full,
                                                baseline_modelling = "bSplines",
                                                shrinkage = TRUE,
                                                withPrediction = FALSE,
                                                havingInt = TRUE)

# Extract the model result
bSplines_model_Int_results_full = Bayesian_Survival_result_Extract(
  bayesian_model_fit = bSplines_model_Int_full,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))
bSplines_model_Int_full_coef <- bSplines_model_Int_results$Beta_bayesian_est[, "mean"]



Data_DBD_PL_Int_full <- stan_data_Constructer_PL(training_dataset = strafied_Data_DBD_int,
                                                 testing_dataset = NULL,
                                                 havingInt = TRUE)

PL_model_Int_full <- Bayesian_Survival_model(stan_data = Data_DBD_PL_Int_full,
                                        baseline_modelling = "none",
                                        shrinkage = TRUE,
                                        withPrediction = FALSE,
                                        havingInt = TRUE,
                                        niter = 10000,
                                        nwarmup = 2000,
                                        thin = 10,
                                        chains = 4
                                        )
# Extract the model result
PL_model_Int_results_full = Bayesian_Survival_result_Extract(
  bayesian_model_fit = PL_model_Int_full,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))

PL_model_Int_full_coef <- PL_model_Int_results_full$Beta_bayesian_est[, "mean"]

  

# Initialize residuals
schoenfeld_res_bSpline <- matrix(NA, nrow = length(strafied_Data_DBD_int$status), ncol = 91)
schoenfeld_res_PL<- matrix(NA, nrow = length(strafied_Data_DBD_int$status), ncol = 91)

# Loop through each event time
for (i in 1:length(strafied_Data_DBD_int$status == 1)) {
  
  t_i <- strafied_Data_DBD_int$obstime[i]
  x_i <- strafied_Data_DBD_int[i, !(names(strafied_Data_DBD_int) %in% c("obstime", "status"))]

  
  # Risk set: those still at risk at time t_i
  risk_set <- which(strafied_Data_DBD_int$obstime >= t_i)
  X_risk <- strafied_Data_DBD_int[risk_set, !(names(strafied_Data_DBD_int) %in% c("obstime", "status"))]
  
  # Compute weights for expected value
  weights_bSpline <- exp(as.matrix(X_risk) %*% as.vector(bSplines_model_Int_full_coef))
  weights_PL <- exp(as.matrix(X_risk) %*% as.vector(PL_model_Int_full_coef))

  
  # Expected covariate values
  expected_x_bSpline <- colSums(X_risk * weights_bSpline) / sum(weights_bSpline)
  expected_x_PL <- colSums(X_risk * weights_PL) / sum(weights_PL)

  # Schoenfeld residuals
  schoenfeld_res_bSpline[i, ] <- as.vector(x_i - expected_x_bSpline)
  schoenfeld_res_PL[i, ] <-   as.vector(x_i - expected_x_PL)
}


# # View residuals for events
# schoenfeld_res_bSpline[!is.na(schoenfeld_res_bSpline[,1]), ]
# schoenfeld_res_PL[!is.na(schoenfeld_res_PL[,1]), ]
# 
# plot(schoenfeld_res_bSpline[!is.na(schoenfeld_res_bSpline[,1]), ])
# line(schoenfeld_res_PL[!is.na(schoenfeld_res_PL[,1]), ])
save.image(file = "./Data/03_results_DBD_Step2.RData")
```

```{r, echo=TRUE}
# STEP 3:  add noise variable
strafied_Data_DBD_int_noise <- strafied_Data_DBD_int
strafied_Data_DBD_int_noise$noise1 <- rnorm(nrow(strafied_Data_DBD_int_noise))
strafied_Data_DBD_int_noise$noise2 <- rnorm(nrow(strafied_Data_DBD_int_noise), 1, 2)

strafied_Data_DBD_int_noise$noise3 <- rnorm(nrow(strafied_Data_DBD_int_noise))
strafied_Data_DBD_int_noise$noise4 <- rnorm(nrow(strafied_Data_DBD_int_noise), 3, 4)
strafied_Data_DBD_int_noise$noise5 <- rnorm(nrow(strafied_Data_DBD_int_noise))
strafied_Data_DBD_int_noise$noise6 <- rnorm(nrow(strafied_Data_DBD_int_noise), 1, 2)
strafied_Data_DBD_int_noise$noise7 <- rnorm(nrow(strafied_Data_DBD_int_noise))
strafied_Data_DBD_int_noise$noise8 <- rnorm(nrow(strafied_Data_DBD_int_noise), 3, 4)
strafied_Data_DBD_int_noise$noise9 <- rnorm(nrow(strafied_Data_DBD_int_noise), 1, 2)


#-----------MODEL 1: bSpline model----------
Data_DBD_bSplines_Int_noise <- stan_data_Constructer_BSpline(
  training_dataset = strafied_Data_DBD_int_noise,
  testing_dataset = NULL,
  obs_window = 3415,
  log_lik_saving = TRUE,
  havingInt = TRUE
)
bSplines_model_Int_noise <- Bayesian_Survival_model(
  stan_data = Data_DBD_bSplines_Int_noise,
  baseline_modelling = "bSplines",
  shrinkage = TRUE,
  withPrediction = FALSE,
  havingInt = TRUE
)

# Extract the model result
bSplines_model_Int_results_noise = Bayesian_Survival_result_Extract(
  bayesian_model_fit = bSplines_model_Int_noise,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))
bSplines_model_Int_noise_coef <- bSplines_model_Int_results_noise$Beta_bayesian_est[, "mean"]
bSplines_model_Int_noise_variableSelection <- bSplines_model_Int_results_noise$variableSelection

#-----------MODEL 2: PL model----------
Data_DBD_PL_Int_noise <- stan_data_Constructer_PL(
  training_dataset = strafied_Data_DBD_int_noise,
  testing_dataset = NULL,
  havingInt = TRUE
)

PL_model_Int_noise <- Bayesian_Survival_model(
  stan_data = Data_DBD_PL_Int_noise,
  baseline_modelling = "none",
  shrinkage = TRUE,
  withPrediction = FALSE,
  havingInt = TRUE,
  niter = 10000,
  nwarmup = 2000,
  thin = 10,
  chains = 4
)

PL_model_Int_results_noise = Bayesian_Survival_result_Extract(
  bayesian_model_fit = PL_model_Int_noise,
  model_type = "none",
  criteria = c("DesignCoefficients",
    "variableSelection",
    "Prediction_SurvivalProb"
  )
)
PL_Int_noise_coef <- PL_model_Int_results_noise$Beta_bayesian_est[, "mean"]
PL_Int_noise_variableSelection <- PL_model_Int_results_noise$variableSelection


name_label = c(names(strafied_Data_DBD_int_noise)[1:91], "noise1", "noise2", "noise3", "noise4", "noise5", "noise6", "noise7", "noise8", "noise9")

par(mfrow = c(2, 1))
plot(bSplines_model_Int_noise_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, ylim = c(-10, 10), xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_Int_noise_variableSelection)) {
  if (bSplines_model_Int_noise_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_Int_noise_coef, type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:100, labels = name_label, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(PL_Int_noise_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, ylim = c(-1, 1), xaxt = "n")
# Add background rectangles
for (i in 1:length(PL_Int_noise_variableSelection)) {
  if (PL_Int_noise_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(PL_Int_noise_coef, type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:100, labels = name_label, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")
save.image(file = "./Data/03_results_DBD_Step3.RData")
```



```{r, echo=TRUE}
# Step 4. scale down the number of knotes and see its performance
#---bSpline model
Data_DBD_bSplines_Int_21 <- stan_data_Constructer_BSpline(
  training_dataset = strafied_Data_DBD_int,
  testing_dataset = NULL,
  obs_window = 3415,
  log_lik_saving = TRUE,
  havingInt = TRUE,
  qnodes = 21
)
Data_DBD_bSplines_Int_15 <- stan_data_Constructer_BSpline(
  training_dataset = strafied_Data_DBD_int,
  testing_dataset = NULL,
  obs_window = 3415,
  log_lik_saving = TRUE,
  havingInt = TRUE,
  qnodes = 15
)

Data_DBD_bSplines_Int_11 <- stan_data_Constructer_BSpline(
  training_dataset = strafied_Data_DBD_int,
  testing_dataset = NULL,
  obs_window = 3415,
  log_lik_saving = TRUE,
  havingInt = TRUE,
  qnodes = 11
)

Data_DBD_bSplines_Int_7 <- stan_data_Constructer_BSpline(
  training_dataset = strafied_Data_DBD_int,
  testing_dataset = NULL,
  obs_window = 3415,
  log_lik_saving = TRUE,
  havingInt = TRUE,
  qnodes = 7
)

bSplines_model_Int_21 <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_Int_21,
                                                baseline_modelling = "bSplines",
                                                shrinkage = TRUE,
                                                withPrediction = FALSE,
                                                havingInt = TRUE)


bSplines_model_Int_15 <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_Int_15,
                                                baseline_modelling = "bSplines",
                                                shrinkage = TRUE,
                                                withPrediction = FALSE,
                                                havingInt = TRUE)

bSplines_model_Int_11 <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_Int_11,
                                                baseline_modelling = "bSplines",
                                                shrinkage = TRUE,
                                                withPrediction = FALSE,
                                                havingInt = TRUE)

bSplines_model_Int_7 <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_Int_7,
                                                baseline_modelling = "bSplines",
                                                shrinkage = TRUE,
                                                withPrediction = FALSE,
                                                havingInt = TRUE)

# Extract the model result
bSplines_model_Int_results_21 = Bayesian_Survival_result_Extract(
  bayesian_model_fit = bSplines_model_Int_21,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))
bSplines_model_Int_results_21_coef <- bSplines_model_Int_results_21$Beta_bayesian_est[, "mean"]
bSplines_model_Int_results_21_varSel <- bSplines_model_Int_results_21$variableSelection

bSplines_model_Int_results_15 = Bayesian_Survival_result_Extract(
  bayesian_model_fit = bSplines_model_Int_15,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))
bSplines_model_Int_results_15_coef <- bSplines_model_Int_results_15$Beta_bayesian_est[, "mean"]
bSplines_model_Int_results_15_varSel <- bSplines_model_Int_results_15$variableSelection

bSplines_model_Int_results_11 = Bayesian_Survival_result_Extract(
  bayesian_model_fit = bSplines_model_Int_11,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))
bSplines_model_Int_results_11_coef <- bSplines_model_Int_results_11$Beta_bayesian_est[, "mean"]
bSplines_model_Int_results_11_varSel <- bSplines_model_Int_results_11$variableSelection

bSplines_model_Int_results_7 = Bayesian_Survival_result_Extract(
  bayesian_model_fit = bSplines_model_Int_7,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))
bSplines_model_Int_results_7_coef <- bSplines_model_Int_results_7$Beta_bayesian_est[, "mean"]
bSplines_model_Int_results_7_varSel <- bSplines_model_Int_results_7$variableSelection


Data_DBD_PL_Int_full <- stan_data_Constructer_PL(training_dataset = strafied_Data_DBD_int,
                                                 testing_dataset = NULL,
                                                 havingInt = TRUE)

PL_model_Int_full <- Bayesian_Survival_model(stan_data = Data_DBD_PL_Int_full,
                                        baseline_modelling = "none",
                                        shrinkage = TRUE,
                                        withPrediction = FALSE,
                                        havingInt = TRUE,
                                        niter = 10000,
                                        nwarmup = 2000,
                                        thin = 10,
                                        chains = 4
                                        )
# Extract the model result
PL_model_Int_results_full = Bayesian_Survival_result_Extract(
  bayesian_model_fit = PL_model_Int_full,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))

PL_model_Int_full_coef <- PL_model_Int_results_full$Beta_bayesian_est[, "mean"]

PL_model_Int_full_varSel <- PL_model_Int_results_full$variableSelection


# Visualize the model results
par(mfrow = c(3, 2))
plot(bSplines_model_Int_results_21_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_Int_results_21_varSel)) {
  if (bSplines_model_Int_results_21_varSel[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_Int_results_21_coef, type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(bSplines_model_Int_results_15_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, xaxt = "n")

# Add background rectangles
for (i in 1:length(bSplines_model_Int_results_15_varSel)) {
  if (bSplines_model_Int_results_15_varSel[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_Int_results_15_coef, type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(bSplines_model_Int_results_11_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_Int_results_11_varSel)) {
  if (bSplines_model_Int_results_11_varSel[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_Int_results_11_coef, type = "o", col = "blue", pch = 16)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(bSplines_model_Int_results_7_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_Int_results_7_varSel)) {
  if (bSplines_model_Int_results_7_varSel[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_Int_results_7_coef, type = "o", col = "blue", pch = 16)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(bSplines_model_Int_results_7_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_Int_results_7_varSel)) {
  if (bSplines_model_Int_results_7_varSel[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_Int_results_7_coef, type = "o", col = "blue", pch = 16)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(PL_model_Int_full_coef, type = "o", col = "darkgreen", xlab = "", ylab = "Beta", main = "", pch = 16, xaxt = "n")

# Add background rectangles
for (i in 1:length(PL_model_Int_full_varSel)) {
  if (PL_model_Int_full_varSel[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(PL_model_Int_full_coef, type = "o", col = "darkgreen", pch = 16)

axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")

save.image(file = "./Data/03_results_DBD_step4.RData")
```

```{r, echo=TRUE}
# Separate the dataset into two small datasets to see the stablility of the estimation of the models
folds <- createFolds(strafied_Data_DBD_int$status, k = 2, list = TRUE, returnTrain = FALSE)

# Cross validation (5-fold)
for (i in seq_along(folds)){
  indices <- folds[[i]]
  model_dataset <- strafied_Data_DBD_int[indices, ]
  
  cat("Fold", i, "\n")
  cat("dataset size:", nrow(model_dataset), "\n")

  # insert your model training and evaluation code here
  #-----------MODEL 1: bSpline model----------
  Data_DBD_bSplines_subset <- stan_data_Constructer_BSpline(
    training_dataset = model_dataset,
    testing_dataset = NULL,
    obs_window = 3415,
    log_lik_saving = TRUE,
    havingInt = TRUE
  )
  bSplines_model_subset <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_subset,
                                                baseline_modelling = "bSplines",
                                                shrinkage = TRUE,
                                                withPrediction = FALSE,
                                                havingInt = TRUE)
  
  #-----------MODEL 2: PL model----------
  Data_DBD_PL_subset <- stan_data_Constructer_PL(
    training_dataset = model_dataset,
    testing_dataset = NULL,
    havingInt = TRUE
  )
  
  PL_model_subset <- Bayesian_Survival_model(
    stan_data = Data_DBD_PL_subset,
    baseline_modelling = "none",
    shrinkage = TRUE,
    withPrediction = FALSE,
    havingInt = TRUE,
    niter = 10000,
    nwarmup = 2000,
    thin = 10,
    chains = 4
  )
  
  
  # Extract the model result
  bSplines_model_subset_results = Bayesian_Survival_result_Extract(
    bayesian_model_fit = bSplines_model_subset,
    model_type = "bSplines",
    criteria = c(
      "DesignCoefficients",
      "variableSelection",
      "Prediction_SurvivalProb"
    )
  )
  
  
  bSplines_model_subset_beta[i,] <- bSplines_model_subset_results$Beta_bayesian_est[, "mean"]
  bSplines_model_subset_variableSelection[i,] <- bSplines_model_subset_results$variableSelection
  
  PL_model_subset_results = Bayesian_Survival_result_Extract(
    bayesian_model_fit = PL_model_subset,
    model_type = "none",
    criteria = c(
      "DesignCoefficients",
      "variableSelection",
      "Prediction_SurvivalProb"
    )
  )
  
  PL_subset_beta[i,] <- PL_model_subset_results$Beta_bayesian_est[, "mean"]
  PL_subset_variableSelection[i,] <- PL_model_subset_results$variableSelection
}


# Visualize the model results
par(mfrow = c(3, 2))
plot(bSplines_model_subset_beta[1,], type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_subset_variableSelection[1,])) {
  if (bSplines_model_subset_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_subset_beta[1,], type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(bSplines_model_subset_beta[2,], type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_subset_variableSelection[2,])) {
  if (bSplines_model_subset_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_subset_beta[2,], type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")



plot(PL_subset_beta[1,], type = "o", col = "darkgreen", xlab = "", ylab = "Beta", main = "", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(PL_subset_variableSelection[1,])) {
  if (PL_subset_variableSelection[1,]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(PL_subset_beta[1,], type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")

plot(PL_subset_beta[2,], type = "o", col = "darkgreen", xlab = "", ylab = "Beta", main = "", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(PL_subset_variableSelection[2,])) {
  if (PL_subset_variableSelection[2,]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(PL_subset_beta[2,], type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")

save.image(file = "./Data/03_results_DBD_step5.RData")
```

```{r, echo=TRUE}
#Build up b-Spline models in the absence of interaction effects
strafied_Data_DBD_int <- includingInter(strafied_Data_DBD)
strafied_Data_DBD_int <- subset(strafied_Data_DBD_int, select = -c(id))
normal_ph <- coxph(Surv(obstime, status) ~ ., strafied_Data_DBD_int)
Data_DBD_bSplines_noInt <- stan_data_Constructer_BSpline(
    training_dataset = strafied_Data_DBD,
    testing_dataset = NULL,
    obs_window = 3415,
    log_lik_saving = TRUE,
    havingInt = FALSE
  )
bSplines_model_noInt <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_noInt, baseline_modelling = "bSplines", shrinkage = TRUE, withPrediction = FALSE, log_likSaving = TRUE, havingInt = FALSE)
diagnostics_bSplines_model_noInt <- summary(bSplines_model_noInt)$summary[, c("Rhat", "n_eff")]




cvl_bSplines_model_noInt <- cross_validated_log_likelihood (bSplines_model_noInt, nrow(strafied_Data_DBD_int))
l_bSplines_model_noInt <- max_log_likelihood (bSplines_model_noInt, nrow(strafied_Data_DBD_int))


  
strafied_Data_DBD_int <- includingInter(strafied_Data_DBD)
Data_DBD_bSplines_withInt <- stan_data_Constructer_BSpline(
    training_dataset = strafied_Data_DBD_int,
    testing_dataset = NULL,
    obs_window = 3415,
    log_lik_saving = TRUE
  )
bSplines_model_withInt <- Bayesian_Survival_model(stan_data = Data_DBD_bSplines_withInt, baseline_modelling = "bSplines", shrinkage = TRUE, withPrediction = FALSE, log_likSaving = TRUE)

diagnostics_bSplines_model_withInt <- summary(bSplines_model_withInt)$summary[, c("Rhat", "n_eff")]

cvl_bSplines_model_withInt <- cross_validated_log_likelihood(bSplines_model_withInt, nrow(strafied_Data_DBD_int))
l_bSplines_model_withInt <- max_log_likelihood(bSplines_model_withInt, nrow(strafied_Data_DBD_int))

output_DBD <- c(cvl_bSplines_model_noInt, cvl_bSplines_model_withInt, l_bSplines_model_noInt, l_bSplines_model_withInt, l_bSplines_model_noInt - cvl_bSplines_model_noInt, l_bSplines_model_withInt - cvl_bSplines_model_withInt)
names(output_DBD) <- c("cvl_bSplines_noInt", "cvl_bSplines_withInt", "l_bSplines_noInt", "l_bSplines_withInt", "d_bSplines_noInt", "d_bSplines_withInt")
output_DBD


model_result_bSplines_withInt <- Bayesian_Survival_result_Extract(bayesian_model_fit = bSplines_model_withInt, model_type = "bSplines", criteria = c("DesignCoefficients", "variableSelection"))
beta_bSplines_withInt = model_result_bSplines_withInt$Beta_bayesian_est[, "mean"]
variableSelection_DBD_bSplines_model_withInt = model_result_bSplines_withInt$variableSelection

stan_data_PL_DBD <- stan_data_Constructer_PL(
      training_dataset = strafied_Data_DBD_int,
      testing_dataset = NULL
    )
model_fit_PL_DBD <- Bayesian_Survival_model(stan_data = stan_data_PL_DBD, baseline_modelling = "none", withPrediction = FALSE, shrinkage = TRUE, log_likSaving = TRUE)

diagnostics_PL_DBD <- summary(model_fit_PL_DBD)$summary[, c("Rhat", "n_eff")]
print(diagnostics_PL_DBD)

#extract the info from the bayesian model fit
model_result_PL_DBD <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_PL_DBD, model_type = "none", criteria = c("DesignCoefficients", "baseline", "variableSelection"))
beta_DBD_PL = model_result_PL_DBD$Beta_bayesian_est[, "mean"]
variableSelection_DBD_PL = model_result_PL_DBD$variableSelection


save.image(file = "./Data/03_results_DBD.RData")
```

## STEP 5: Visulize the beta estimation
```{r, echo=TRUE}
load(file = "./Data/03_results_DBD.RData")
par(mfrow = c(2, 1))
plot(beta_bSplines_withInt, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, ylim = c(-10, 10), xaxt = "n")
# Add background rectangles
for (i in 1:length(variableSelection_DBD_bSplines_model_withInt)) {
  if (variableSelection_DBD_bSplines_model_withInt[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(beta_bSplines_withInt, type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(beta_DBD_PL, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, ylim = c(-1, 1), xaxt = "n")
# Add background rectangles
for (i in 1:length(variableSelection_DBD_bSplines_model_withInt)) {
  if (variableSelection_DBD_PL[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(beta_DBD_PL, type = "o", col = "darkgreen", pch = 16)
abline(a = 0, b =0, col = "red")



# 
# for (i in 1:length(variableSelection_DBD_PL)) {
#   if (variableSelection_DBD_PL[i]) {
#     rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
#   }
# }
# 
# lines(beta_bSplines_withInt, type = "o", col = "blue", pch = 16)
# lines(beta_DBD_PL, type = "o", col = "green", pch = 16)
# legend("top", legend = c("beta_bSplines_withInt", "beta_DBD_PL"), col = c("blue", "green"), pch = 16, lty = 1, horiz = TRUE) 
```
# Section 2: Data analysis for DCD
## STEP 1: estimate the Betas for DCD
```{r, echo=TRUE}
obs_window = 3415 #max(df_using$time_tx_date_max2)
strafied_Data_DCD_int <- includingInter(strafied_Data_DCD)
strafied_Data_DCD_int <- subset(strafied_Data_DCD_int, select = -c(id))
strafied_Data_DCD_int_noise <- strafied_Data_DCD_int
strafied_Data_DCD_int_noise$noise1 <- rnorm(nrow(strafied_Data_DCD_int_noise))
strafied_Data_DCD_int_noise$noise2 <- rnorm(nrow(strafied_Data_DCD_int_noise), 1, 2)
strafied_Data_DCD_int_noise$noise3 <- rnorm(nrow(strafied_Data_DCD_int_noise))
strafied_Data_DCD_int_noise$noise4 <- rnorm(nrow(strafied_Data_DCD_int_noise), 3, 4)
strafied_Data_DCD_int_noise$noise5 <- rnorm(nrow(strafied_Data_DCD_int_noise))
strafied_Data_DCD_int_noise$noise6 <- rnorm(nrow(strafied_Data_DCD_int_noise), 1, 2)
strafied_Data_DCD_int_noise$noise7 <- rnorm(nrow(strafied_Data_DCD_int_noise))
strafied_Data_DCD_int_noise$noise8 <- rnorm(nrow(strafied_Data_DCD_int_noise), 3, 4)
strafied_Data_DCD_int_noise$noise9 <- rnorm(nrow(strafied_Data_DCD_int_noise), 1, 2)

stan_data_bSpline_DCD <- stan_data_Constructer_BSpline(
      training_dataset = strafied_Data_DCD_int_noise,
      testing_dataset = NULL,
      obs_window = 3415
    )

stan_data_PL_DCD <- stan_data_Constructer_PL(
      training_dataset = strafied_Data_DCD_int_noise,
      testing_dataset = NULL
    )

model_fit_bSpline_DCD <- Bayesian_Survival_model(stan_data = stan_data_bSpline_DCD, baseline_modelling = "bSplines", withPrediction = FALSE, shrinkage = TRUE)

model_fit_PL_DCD <- Bayesian_Survival_model(stan_data = stan_data_PL_DCD, baseline_modelling = "none", withPrediction = FALSE, shrinkage = TRUE)

#model diagnotics
diagnostics_bSpline_DCD <- summary(model_fit_bSpline_DCD)$summary[, c("Rhat", "n_eff")]
diagnostics_PL_DCD <- summary(model_fit_PL_DCD)$summary[, c("Rhat", "n_eff")]
print(diagnostics_bSpline_DCD)
print(diagnostics_PL_DCD)

#extract the info from the bayesian model fit
model_result_bSpline_DCD <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_bSpline_DCD, model_type = "none", criteria = c("DesignCoefficients", "baseline", "variableSelection"))

model_result_PL_DCD <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_PL_DCD, model_type = "none", criteria = c("DesignCoefficients", "baseline", "variableSelection"))

bSplines_model_Int_noise_coef_DCD = model_result_bSpline_DCD$Beta_bayesian_est[, "mean"]
bSplines_model_Int_noise_variableSelection_DCD = model_result_bSpline_DCD$variableSelection

PL_Int_noise_coef_DCD = model_result_PL_DCD$Beta_bayesian_est[, "mean"]
PL_Int_noise_variableSelection_DCD = model_result_PL_DCD$variableSelection


name_label_DCD = c(names(strafied_Data_DCD_int_noise))#, "noise1", "noise2", "noise3", "noise4", "noise5", "noise6", "noise7", "noise8", "noise9")

par(mfrow = c(2, 1))
plot(bSplines_model_Int_noise_coef_DCD, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, ylim = c(-10, 10), xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_Int_noise_variableSelection_DCD)) {
  if (bSplines_model_Int_noise_variableSelection_DCD[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_Int_noise_coef_DCD, type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:116, labels = name_label_DCD, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(PL_Int_noise_coef_DCD, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, ylim = c(-1, 1), xaxt = "n")
# Add background rectangles
for (i in 1:length(PL_Int_noise_variableSelection_DCD)) {
  if (PL_Int_noise_variableSelection_DCD[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(PL_Int_noise_coef_DCD, type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:116, labels = name_label_DCD, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")

#cross_val_metric_DBD <- cross_validation(whole_dataset = strafied_Data_DBD_int, baseline_modelling = "bSplines", num_folds = 5, obs_window = 3415)
save.image(file = "./Data/03_results_DCD_step3.RData")
```
## STEP 2: visualize DCD results
```{r, echo=TRUE}
load(file = "./Data/03_results_DCD.RData")
plot(beta_bSplines_withInt, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, ylim = c(-10, 10), xaxt = "n")
# Add background rectangles
for (i in 1:length(variableSelection_DBD_bSplines_model_withInt)) {
  if (variableSelection_DBD_bSplines_model_withInt[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(beta_bSplines_withInt, type = "o", col = "blue", pch = 16)
# lines(beta_bSplines_withInt, type = "o", col = "lightgreen", pch = 16)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
```


