---
title: "03_Real_Data_Analysis"
author: "Yufang Wang"
date: "2025-03-18"
output: pdf_document
---

# Step 1: Set up the environment
```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#G:/MasterThesis/Code/"
source("./function_file/Functions.R")
source("./function_file/stan_constructor.R")

install_and_load <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {
      install.packages(pkg, dependencies = TRUE)
    }
    library(pkg, character.only = TRUE) }
  
}

# List of required packages
required_packages <- c("rstan", "MASS", "rstantools", "coda", "readr", "survival", "splines2", "dplyr", "simsurv", "Hmisc", "caret", "corrplot","ggplot2", "loo", "survival", "caret")
# Install and/or load packages
install_and_load(required_packages)
```


# Step 2: Organize and strafied the real-world data
```{r, echo=TRUE}
real_df <- readRDS("./Data/imputed_NOTR_DGF.rds")
# sum(!complete.cases(real_df))
# mean(real_df$status == "graftloss")
# mean(real_df$status == "alive")
# mean(real_df$status == "death")

# # Reversed KM for follow-up analysis
# fit <- survfit(Surv(real_df$time, real_df$status != "graftloss") ~ 1)
# plot(fit)
# abline(h = 0.5, col = "red", lty = 2)
# 
# str(real_df)
real_df <- real_df[, !names(real_df) %in% "ID"]

# set the factor variable being sum-to-zero encoded
contrasts(real_df$Recipientsex) <- contr.sum(levels(real_df$Recipientsex))
contrasts(real_df$Donorsex) <- contr.sum(levels(real_df$Donorsex))
contrasts(real_df$Smoking) <- contr.sum(levels(real_df$Smoking))
contrasts(real_df$InitialPrimaryDiseaseET_regroup) <- contr.sum(levels(real_df$InitialPrimaryDiseaseET_regroup))
contrasts(real_df$Donorcauseofdeath_group) <- contr.sum(levels(real_df$Donorcauseofdeath_group))


# center the numeric variables
real_df$Recipientage <- scale(real_df$Recipientage)
real_df$Dialysisdaysrenine <- scale(real_df$Dialysisdaysrenine)
real_df$Donorage <- scale(real_df$Donorage)
real_df$Lastcreatininemgdl <- scale(real_df$Lastcreatininemgdl)
real_df$Warm_ischaemic_period_1 <- scale(real_df$Warm_ischaemic_period_1)
real_df$Cold_ischaemic_period <- scale(real_df$Cold_ischaemic_period)
real_df$HLA_mismatch <- scale(real_df$HLA_mismatch)
real_df$DonorBMI <- scale(real_df$DonorBMI)
real_df$Recipient_BMI <- scale(real_df$Recipient_BMI)
#

# print(colnames(real_df)[factorName])

real_df <- real_df[, !(names(real_df) %in% "InitialOnmachineindicator")]
real_df$Donorcauseofdeath_group <- ifelse(real_df$Donorcauseofdeath_group == "Cardiac", "Cardiac", "Others")
real_df$Donorcauseofdeath_group <- factor(real_df$Donorcauseofdeath_group)
contrasts(real_df$Donorcauseofdeath_group) <- contr.sum(levels(real_df$Donorcauseofdeath_group))

real_df$InitialPrimaryDiseaseET_regroup <- ifelse(real_df$InitialPrimaryDiseaseET_regroup == "Diabetes Mellitus", "Diabetes", "Others")
real_df$InitialPrimaryDiseaseET_regroup <- factor(real_df$InitialPrimaryDiseaseET_regroup)
contrasts(real_df$InitialPrimaryDiseaseET_regroup) <- contr.sum(levels(real_df$InitialPrimaryDiseaseET_regroup))


combined_Data <- subset(real_df, select = -Warm_ischaemic_period_1)
```

# Descriptive data analysis
```{r, echo=TRUE}

```

```{r, echo=TRUE}
real_df_simple <- subset(real_df, select = -c(Smoking, Donorcauseofdeath_group, Dialysisdaysrenine, Recipientsex, Recipient_BMI, Warm_ischaemic_period_1))
# set the factor variable being sum-to-zero encoded
contrasts(real_df_simple$Donorsex) <- contr.sum(levels(real_df_simple$Donorsex))
contrasts(real_df_simple$TypecadavericDBDDCD) <- contr.sum(levels(real_df_simple$TypecadavericDBDDCD))
contrasts(real_df_simple$InitialPrimaryDiseaseET_regroup) <- contr.sum(levels(real_df_simple$InitialPrimaryDiseaseET_regroup))



# center the numeric variables
real_df_simple$Recipientage <- scale(real_df_simple$Recipientage)
real_df_simple$Donorage <- scale(real_df_simple$Donorage)
real_df_simple$Lastcreatininemgdl <- scale(real_df_simple$Lastcreatininemgdl)
real_df_simple$Cold_ischaemic_period <- scale(real_df_simple$Cold_ischaemic_period)
real_df_simple$HLA_mismatch <- scale(real_df_simple$HLA_mismatch)
real_df_simple$DonorBMI <- scale(real_df_simple$DonorBMI)


combined_Data_Simple <- real_df_simple
```

# Check whether or not each level have sufficient events
```{r, echo=TRUE}
# Identify categorical variables
categorical_vars <- names(combined_Data)[sapply(combined_Data, function(x) is.factor(x) || is.character(x))]

# Print the categorical variables
print(categorical_vars)

for (cvars in categorical_vars){
  if (cvars != "status"){
    print(table(combined_Data[[cvars]], combined_Data$status))
  }
}
```

# Section 1: include all variables and see whether or not it is possible for the get the model converenge

## Step 4: Verify the existence of interaction effects
```{r, echo=TRUE}
combined_Data_int <- includingInter(combined_Data)
combined_Data_int <- subset(combined_Data_int, select = -c(id))

combined_Data_Simple_int <- includingInter(combined_Data_Simple)
combined_Data_Simple_int <- subset(combined_Data_Simple_int, select = -c(id))
```

```{r, echo=TRUE}
# STEP 3:  add noise variable
combined_Data_int_noise <- combined_Data_int
combined_Data_int_noise$noise1 <- rnorm(nrow(combined_Data_int_noise))
combined_Data_int_noise$noise2 <- rnorm(nrow(combined_Data_int_noise), 1, 2)
combined_Data_int_noise$noise3 <- rnorm(nrow(combined_Data_int_noise), 3, 4)

combined_Data_Simple_int_noise <- combined_Data_Simple_int
combined_Data_Simple_int_noise$noise1 <- rnorm(nrow(combined_Data_Simple_int_noise))
combined_Data_Simple_int_noise$noise2 <- rnorm(nrow(combined_Data_Simple_int_noise), 1, 2)
combined_Data_Simple_int_noise$noise3 <- rnorm(nrow(combined_Data_Simple_int_noise), 3, 4)

#-----------MODEL 1.1: Cox regression--------
cox_regression <- coxph(Surv(as.numeric(obstime), status) ~., data = combined_Data_int_noise)
combined_Data_int_noise_cox_regression_result <- summary(cox_regression)
combined_Data_int_noise_cox_regression_result_coef <- as.matrix(combined_Data_int_noise_cox_regression_result$coefficients[, "coef"])
combined_Data_int_noise_cox_regression_result_variableSelection <- as.matrix((combined_Data_int_noise_cox_regression_result$coefficients[, "Pr(>|z|)"] *105) < 0.05)


#-----------MODEL 1.2: bSpline model----------
combined_Data_int_noise_bSpline <- stan_data_Constructer_BSpline(
  training_dataset = combined_Data_int_noise,
  testing_dataset = NULL,
  obs_window = 3415,
  log_lik_saving = TRUE,
  havingInt = TRUE
)
combined_Data_int_noise_bSpline_model <- Bayesian_Survival_model(
  stan_data = combined_Data_int_noise_bSpline,
  baseline_modelling = "bSplines",
  shrinkage = TRUE,
  withPrediction = FALSE,
  havingInt = TRUE,
  niter = 10000,
  nwarmup = 2000,
  thin = 10,
  chains = 1
)

# Extract the model result
combined_Data_int_noise_bSpline_model_result = Bayesian_Survival_result_Extract(
  bayesian_model_fit = combined_Data_int_noise_bSpline_model,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))
combined_Data_int_noise_bSpline_model_result_coef <- combined_Data_int_noise_bSpline_model_result$Beta_bayesian_est[, "mean"]
combined_Data_int_noise_bSpline_model_result_variableSelection <- combined_Data_int_noise_bSpline_model_result$variableSelection

#-----------MODEL 1.3: PL model----------
combined_Data_int_noise_PL <- stan_data_Constructer_PL(
  training_dataset = combined_Data_int_noise,
  testing_dataset = NULL,
  havingInt = TRUE
)

combined_Data_int_noise_PL_model <- Bayesian_Survival_model(
  stan_data = combined_Data_int_noise_PL,
  baseline_modelling = "none",
  shrinkage = TRUE,
  withPrediction = FALSE,
  havingInt = TRUE,
  niter = 10000,
  nwarmup = 2000,
  thin = 10,
  chains = 1
)

combined_Data_int_noise_PL_model_result = Bayesian_Survival_result_Extract(
  bayesian_model_fit = combined_Data_int_noise_PL_model,
  model_type = "none",
  criteria = c("DesignCoefficients",
    "variableSelection",
    "Prediction_SurvivalProb"
  )
)
combined_Data_int_noise_PL_model_result_coef <- combined_Data_int_noise_PL_model_result$Beta_bayesian_est[, "mean"]
combined_Data_int_noise_PL_model_result_variableSelection <- combined_Data_int_noise_PL_model_result$variableSelection


#-----------MODEL 2.1: Cox regression--------
cox_regression_Simple <- coxph(Surv(as.numeric(obstime), status) ~., data = combined_Data_Simple_int_noise)
combined_Data_int_noise_cox_regression_Simple_result <- summary(cox_regression_Simple)
combined_Data_int_noise_cox_regression_Simple_result_coef <- as.matrix(combined_Data_int_noise_cox_regression_Simple_result$coefficients[, "coef"])
combined_Data_int_noise_cox_regression_Simple_result_variableSelection <- as.matrix((combined_Data_int_noise_cox_regression_Simple_result$coefficients[, "Pr(>|z|)"] *48) < 0.05)


#-----------MODEL 2.2: bSpline model----------
combined_Data_int_noise_bSpline_Simple <- stan_data_Constructer_BSpline(
  training_dataset = combined_Data_Simple_int_noise,
  testing_dataset = NULL,
  obs_window = 3415,
  log_lik_saving = TRUE,
  havingInt = TRUE
)
combined_Data_int_noise_bSpline_model_Simple <- Bayesian_Survival_model(
  stan_data = combined_Data_int_noise_bSpline_Simple,
  baseline_modelling = "bSplines",
  shrinkage = TRUE,
  withPrediction = FALSE,
  havingInt = TRUE,
  niter = 10000,
  nwarmup = 2000,
  thin = 10,
  chains = 1
)

# Extract the model result
combined_Data_int_noise_bSpline_model_Simple_result = Bayesian_Survival_result_Extract(
  bayesian_model_fit = combined_Data_int_noise_bSpline_model_Simple,
  model_type = "bSplines",
  criteria = c("DesignCoefficients", "variableSelection", "Prediction_SurvivalProb"))
combined_Data_int_noise_bSpline_model_Simple_result_coef <- combined_Data_int_noise_bSpline_model_Simple_result$Beta_bayesian_est[, "mean"]
combined_Data_int_noise_bSpline_model_Simple_result_variableSelection <- combined_Data_int_noise_bSpline_model_Simple_result$variableSelection

#-----------MODEL 2.3: PL model----------
combined_Data_int_noise_PL_Simple <- stan_data_Constructer_PL(
  training_dataset = combined_Data_Simple_int_noise,
  testing_dataset = NULL,
  havingInt = TRUE
)

combined_Data_int_noise_PL_model_Simple <- Bayesian_Survival_model(
  stan_data = combined_Data_int_noise_PL_Simple,
  baseline_modelling = "none",
  shrinkage = TRUE,
  withPrediction = FALSE,
  havingInt = TRUE,
  niter = 10000,
  nwarmup = 2000,
  thin = 10,
  chains = 1
)

combined_Data_int_noise_PL_model_Simple_result = Bayesian_Survival_result_Extract(
  bayesian_model_fit = combined_Data_int_noise_PL_model_Simple,
  model_type = "none",
  criteria = c("DesignCoefficients",
    "variableSelection",
    "Prediction_SurvivalProb"
  )
)
combined_Data_int_noise_PL_model_Simple_result_coef <- combined_Data_int_noise_PL_model_Simple_result$Beta_bayesian_est[, "mean"]
combined_Data_int_noise_PL_model_Simple_result_variableSelection <- combined_Data_int_noise_PL_model_Simple_result$variableSelection

save.image(file = "./Data/03_results_combined_Step3_includeSimpleData.RData")
```

```{r, echo=TRUE}
load(file = "./Data/03_results_combined_Step3_includeSimpleData.RData")
name_label = c(names(combined_Data_int_noise)[1:105], "noise1", "noise2", "noise3")


par(mfrow = c(3, 1))
plot(combined_Data_int_noise_bSpline_model_result_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, ylim = c(-3, 3), xaxt = "n")
# Add background rectangles
for (i in 1:length(combined_Data_int_noise_bSpline_model_result_variableSelection)) {
  if (combined_Data_int_noise_bSpline_model_result_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(combined_Data_int_noise_bSpline_model_result_coef, type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:108, labels = name_label, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")

plot(combined_Data_int_noise_cox_regression_result_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, ylim = c(-1, 1), xaxt = "n")
# Add background rectangles
for (i in 1:length(combined_Data_int_noise_cox_regression_result_variableSelection)) {
  if (combined_Data_int_noise_cox_regression_result_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(combined_Data_int_noise_cox_regression_result_coef, type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:108, labels = name_label, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(combined_Data_int_noise_PL_model_result_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, ylim = c(-1, 1), xaxt = "n")
# Add background rectangles
for (i in 1:length(combined_Data_int_noise_PL_model_result_variableSelection)) {
  if (combined_Data_int_noise_PL_model_result_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(combined_Data_int_noise_PL_model_result_coef, type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:108, labels = name_label, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


# -----------------------------   Figure 2   -----------------------------------------
name_label_Simple = c(names(combined_Data_int_noise)[1:45], "noise1", "noise2", "noise3")


par(mfrow = c(3, 1))
plot(combined_Data_int_noise_bSpline_model_Simple_result_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, ylim = c(-2, 2), xaxt = "n")
# Add background rectangles
for (i in 1:length(combined_Data_int_noise_bSpline_model_Simple_result_variableSelection)) {
  if (combined_Data_int_noise_bSpline_model_Simple_result_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(combined_Data_int_noise_bSpline_model_Simple_result_coef, type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:48, labels = name_label_Simple, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")

plot(combined_Data_int_noise_cox_regression_Simple_result_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, ylim = c(-1, 1), xaxt = "n")
# Add background rectangles
for (i in 1:length(combined_Data_int_noise_cox_regression_Simple_result_variableSelection)) {
  if (combined_Data_int_noise_cox_regression_Simple_result_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(combined_Data_int_noise_cox_regression_Simple_result_coef, type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:48, labels = name_label_Simple, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(combined_Data_int_noise_PL_model_Simple_result_coef, type = "o", col = "blue", xlab = "", ylab = "Beta", main = "", pch = 16, ylim = c(-1, 1), xaxt = "n")
# Add background rectangles
for (i in 1:length(combined_Data_int_noise_PL_model_Simple_result_variableSelection)) {
  if (combined_Data_int_noise_PL_model_Simple_result_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(combined_Data_int_noise_PL_model_Simple_result_coef, type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:48, labels = name_label_Simple, las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")
```

# Cross validation, 10-folds
```{r, echo=TRUE}
set.seed(123456)

# Number of folds
k <- 10


# Assuming p is the number of coefficients
p <- 105

# Preallocate lists to store results across repetitions
folds <- createFolds(combined_Data_int$status, k = k, list = TRUE)


bSplines_model_C_INDEX_Simple = bSplines_model_C_INDEX = rep(NA, k)
coxRegression_C_INDEX_Simple = coxRegression_C_INDEX = rep(NA, k)
PL_C_INDEX_Simple = PL_C_INDEX = rep(NA, k)


for (i in seq_along(folds)) {
  cat("Repetition", i, "\n")
  
  indices <- folds[[i]]
  training_dataset <- combined_Data_int[-indices,]
  testing_dataset <- combined_Data_int[indices,]
  
  
  training_dataset_Simple <- combined_Data_Simple_int[-indices,]
  testing_dataset2_Simple <- combined_Data_Simple_int[indices,]
  
  cat("Fold", i, "\n")
  cat("Dataset size:", nrow(training_dataset), "\n")

  
  # Model 1.1 b-Splines model-------
  Data_bSplines <- stan_data_Constructer_BSpline(
      training_dataset = training_dataset,
      testing_dataset = testing_dataset,
      obs_window = 3415,
      log_lik_saving = FALSE,
      havingInt = TRUE
    )
  bSplines_model <-
      Bayesian_Survival_model(
        stan_data = Data_bSplines,
        baseline_modelling = "bSplines",
        shrinkage = TRUE,
        withPrediction = TRUE,
        havingInt = TRUE,
        niter = 10000,
        nwarmup = 2000,
        thin = 10,
        chains = 1
      )
  # Extract the model result
  bSplines_model_results = Bayesian_Survival_result_Extract(
      bayesian_model_fit = bSplines_model,
      model_type = "bSplines",
      criteria = c("Prediction_SurvivalProb")
    )
  bSplines_model_Prediction_SurvivalProb <- as.vector(bSplines_model_results$eta_pred)
  bSplines_model_C_INDEX[i] <- rcorr.cens(-bSplines_model_Prediction_SurvivalProb, Surv(testing_dataset$obstime, testing_dataset$status))["C Index"] 
  
  # Model 2.1 b-Splines model for simplifed data -------
  Data_bSplines_Simple <- stan_data_Constructer_BSpline(
      training_dataset = training_dataset_Simple,
      testing_dataset = testing_dataset2_Simple,
      obs_window = 3415,
      log_lik_saving = FALSE,
      havingInt = TRUE
    )
  bSplines_model_Simple <-
      Bayesian_Survival_model(
        stan_data = Data_bSplines_Simple,
        baseline_modelling = "bSplines",
        shrinkage = TRUE,
        withPrediction = TRUE,
        havingInt = TRUE,
        niter = 10000,
        nwarmup = 2000,
        thin = 10,
        chains = 1
      )
   # Extract the model result
  bSplines_model_results_Simple = Bayesian_Survival_result_Extract(
      bayesian_model_fit = bSplines_model_Simple,
      model_type = "bSplines",
      criteria = c("Prediction_SurvivalProb")
    )
  bSplines_model_Prediction_SurvivalProb_Simple <- bSplines_model_results_Simple$eta_pred
  bSplines_model_C_INDEX_Simple <- rcorr.cens(-bSplines_model_Prediction_SurvivalProb_Simple, Surv(testing_dataset$obstime, testing_dataset$status))["C Index"] 

    #-----------MODEL 1.2: Cox regression ----------
    cox_regression <- coxph(Surv(as.numeric(obstime), status) ~ ., data = training_dataset)
    coxRegression_SurvivalProb <- predict(cox_regression, newdata = testing_dataset, type = "lp")
    coxRegression_C_INDEX <- rcorr.cens(-coxRegression_SurvivalProb, Surv(testing_dataset$obstime, testing_dataset$status))["C Index"] 
    
    #-----------MODEL 2.2: Cox regression ----------
    cox_regression_Simple <- coxph(Surv(as.numeric(obstime), status) ~ ., data = training_dataset_Simple)
    coxRegression_SurvivalProb_Simple <- predict(cox_regression_Simple, newdata = testing_dataset2_Simple, type = "lp")
    coxRegression_C_INDEX_Simple <- rcorr.cens(-coxRegression_SurvivalProb_Simple, Surv(testing_dataset$obstime, testing_dataset$status))["C Index"] 
    
    #-----------MODEL 1.3: PL model----------
    Data_PL <- stan_data_Constructer_PL(
      training_dataset = training_dataset,
      testing_dataset = testing_dataset,
      havingInt = TRUE
    )
    
    PL_model <- Bayesian_Survival_model(
      stan_data = Data_PL,
      baseline_modelling = "none",
      shrinkage = TRUE,
      withPrediction = TRUE,
      havingInt = TRUE,
      niter = 10000,
      nwarmup = 2000,
      thin = 10,
      chains = 1
    )
    PL_results = Bayesian_Survival_result_Extract(
      bayesian_model_fit = PL_model,
      model_type = "none",
      criteria = c("Prediction_SurvivalProb")
    )
    PL_Prediction_SurvivalProb <- PL_results$eta_pred
    PL_C_INDEX <- rcorr.cens(-PL_Prediction_SurvivalProb, Surv(testing_dataset$obstime, testing_dataset$status))["C Index"] 
    
    #-----------MODEL 2.3: PL model----------
    Data_PL_Simple <- stan_data_Constructer_PL(
      training_dataset = training_dataset_Simple,
      testing_dataset = testing_dataset2_Simple,
      havingInt = TRUE
    )
    
    PL_model_Simple <- Bayesian_Survival_model(
      stan_data = Data_PL_Simple,
      baseline_modelling = "none",
      shrinkage = TRUE,
      withPrediction = TRUE,
      havingInt = TRUE,
      niter = 10000,
      nwarmup = 2000,
      thin = 10,
      chains = 1
    )
    PL_results_Simple = Bayesian_Survival_result_Extract(
      bayesian_model_fit = PL_model_Simple,
      model_type = "none",
      criteria = c("Prediction_SurvivalProb")
    )
    PL_Prediction_SurvivalProb_Simple <- PL_results_Simple$eta_pred
    PL_C_INDEX_Simple <- rcorr.cens(-PL_Prediction_SurvivalProb_Simple, Surv(testing_dataset$obstime, testing_dataset$status))["C Index"] 
}

save.image(file = "./Data/03_results_combined_Step4_includSimplifiedData.RData")
```


```{r, echo=TRUE}
load(file = "./Data/03_results_combined_Step4_includSimplifiedData.RData")
par(mfrow = c(1, 2))

C_index <- list(bSplines = bSplines_model_C_INDEX, CoxRegression = coxRegression_C_INDEX,  PL = PL_C_INDEX)
boxplot(C_index, names = c("BayesianBSplines", "CoxRegression", "BayesianPL"), col = c("orange", "green","purple"), main = "C-index", xlab = "", ylab = "C-index", ylim = c(0, 1))


C_index_Simplified <- list(bSplines = bSplines_model_C_INDEX_Simple, CoxRegression = coxRegression_C_INDEX_Simple, PL = PL_C_INDEX_Simple)
boxplot(C_index_Simplified, names = c("BayesianBSplines", "CoxRegression", "BayesianPL"), col = c("orange", "green","purple"), main = "C-index", xlab = "", ylab = "C-index", ylim = c(0, 1))
```


```{r, echo=TRUE}
# Step 4. separate the dataset randomly into two and compare the stability of the model across different sub dataset
# Separate the dataset into two small datasets to see the stablility of the estimation of the models
set.seed(123456)

# Number of folds
k <- 2 

# Number of repetitions
n_repeats <- 10

# Assuming p is the number of coefficients
p <- 105
p1 <- 45

# Preallocate lists to store results across repetitions
bSplines_beta_list <- vector("list", n_repeats)
bSplines_varSel_list <- vector("list", n_repeats)
PL_beta_list <- vector("list", n_repeats)
PL_varSel_list <- vector("list", n_repeats)
cox_beta_list <- vector("list", n_repeats)
cox_varSel_list <- vector("list", n_repeats)

bSplines_beta_list2 <- vector("list", n_repeats)
bSplines_varSel_list2 <- vector("list", n_repeats)
PL_beta_list2 <- vector("list", n_repeats)
PL_varSel_list2 <- vector("list", n_repeats)
cox_beta_list2 <- vector("list", n_repeats)
cox_varSel_list2 <- vector("list", n_repeats)

bSplines_beta_list_Simple <- vector("list", n_repeats)
bSplines_varSel_list_Simple <- vector("list", n_repeats)
PL_beta_list_Simple <- vector("list", n_repeats)
PL_varSel_list_Simple <- vector("list", n_repeats)
cox_beta_list_Simple <- vector("list", n_repeats)
cox_varSel_list_Simple <- vector("list", n_repeats)

bSplines_beta_list2_Simple <- vector("list", n_repeats)
bSplines_varSel_list2_Simple <- vector("list", n_repeats)
PL_beta_list2_Simple <- vector("list", n_repeats)
PL_varSel_list2_Simple <- vector("list", n_repeats)
cox_beta_list2_Simple <- vector("list", n_repeats)
cox_varSel_list2_Simple <- vector("list", n_repeats)

for (r in 1:n_repeats) {
  cat("Repetition", r, "\n")
  
  # Generate new folds for each repetition
  folds <- createFolds(combined_Data_int$status, k = k, list = TRUE)
  
  # Preallocate matrices for this repetition
  bSplines_model_beta <- matrix(NA, nrow = k, ncol = p)
  bSplines_model_variableSelection <- matrix(NA, nrow = k, ncol = p)
  PL_beta <- matrix(NA, nrow = k, ncol = p)
  PL_variableSelection <- matrix(NA, nrow = k, ncol = p)
  cox_beta <- matrix(NA, nrow = k, ncol = p)
  cox_variableSelection <- matrix(NA, nrow = k, ncol = p)
  
  
  bSplines_model_beta2 <- matrix(NA, nrow = k, ncol = p)
  bSplines_model_variableSelection2 <- matrix(NA, nrow = k, ncol = p)
  PL_beta2 <- matrix(NA, nrow = k, ncol = p)
  PL_variableSelection2 <- matrix(NA, nrow = k, ncol = p)
  cox_beta2 <- matrix(NA, nrow = k, ncol = p)
  cox_variableSelection2 <- matrix(NA, nrow = k, ncol = p)
  
  #---------- For simplified dataset---------------
  bSplines_model_beta_Simple <- matrix(NA, nrow = k, ncol = p1)
  bSplines_model_variableSelection_Simple <- matrix(NA, nrow = k, ncol = p1)
  PL_beta_Simple <- matrix(NA, nrow = k, ncol = p1)
  PL_variableSelection_Simple <- matrix(NA, nrow = k, ncol = p1)
  cox_beta_Simple <- matrix(NA, nrow = k, ncol = p1)
  cox_variableSelection_Simple <- matrix(NA, nrow = k, ncol = p1)
  
  
  bSplines_model_beta2_Simple <- matrix(NA, nrow = k, ncol = p1)
  bSplines_model_variableSelection2_Simple <- matrix(NA, nrow = k, ncol = p1)
  PL_beta2_Simple <- matrix(NA, nrow = k, ncol = p1)
  PL_variableSelection2_Simple <- matrix(NA, nrow = k, ncol = p1)
  cox_beta2_Simple <- matrix(NA, nrow = k, ncol = p1)
  cox_variableSelection2_Simple <- matrix(NA, nrow = k, ncol = p1)
  
  
  for (i in seq_along(folds)) {
    indices <- folds[[i]]
    training_dataset <- combined_Data_int[-indices,]
    training_dataset2 <- combined_Data_int[indices,]
    
    training_dataset_Simple <- combined_Data_Simple_int[-indices,]
    training_dataset2_Simple <- combined_Data_Simple_int[indices,]
    
    cat("Fold", i, "\n")
    cat("Dataset size:", nrow(training_dataset), "\n")
    
    # insert your model training and evaluation code here
    #-----------MODEL 1.1: bSpline model----------
    Data_bSplines <- stan_data_Constructer_BSpline(
      training_dataset = training_dataset,
      testing_dataset = NULL,
      obs_window = 3415,
      log_lik_saving = FALSE,
      havingInt = TRUE
    )
    bSplines_model <-
      Bayesian_Survival_model(
        stan_data = Data_bSplines,
        baseline_modelling = "bSplines",
        shrinkage = TRUE,
        withPrediction = FALSE,
        havingInt = TRUE,
        niter = 10000,
        nwarmup = 2000,
        thin = 10,
        chains = 1
      )
    
    Data_bSplines2 <- stan_data_Constructer_BSpline(
      training_dataset = training_dataset2,
      testing_dataset = NULL,
      obs_window = 3415,
      log_lik_saving = FALSE,
      havingInt = TRUE
    )
    bSplines_model2 <-
      Bayesian_Survival_model(
        stan_data = Data_bSplines2,
        baseline_modelling = "bSplines",
        shrinkage = TRUE,
        withPrediction = FALSE,
        havingInt = TRUE,
        niter = 10000,
        nwarmup = 2000,
        thin = 10,
        chains = 1
      )
    
    
    #-----------MODEL 1.2: Cox regression ----------
    cox_regression <- coxph(Surv(as.numeric(obstime), status) ~ ., data = training_dataset)
    cox_regression_result <- summary(cox_regression)
    
    cox_regression2 <- coxph(Surv(as.numeric(obstime), status) ~ ., data = training_dataset2)
    cox_regression_result2 <- summary(cox_regression2)
   
    
    #-----------MODEL 1.3: PL model----------
    Data_PL <- stan_data_Constructer_PL(
      training_dataset = training_dataset,
      testing_dataset = NULL,
      havingInt = TRUE
    )
    
    PL_model <- Bayesian_Survival_model(
      stan_data = Data_PL,
      baseline_modelling = "none",
      shrinkage = TRUE,
      withPrediction = FALSE,
      havingInt = TRUE,
      niter = 10000,
      nwarmup = 2000,
      thin = 10,
      chains = 1
    )
    
    Data_PL2 <- stan_data_Constructer_PL(
      training_dataset = training_dataset2,
      testing_dataset = NULL,
      havingInt = TRUE
    )
    
    PL_model2 <- Bayesian_Survival_model(
      stan_data = Data_PL2,
      baseline_modelling = "none",
      shrinkage = TRUE,
      withPrediction = FALSE,
      havingInt = TRUE,
      niter = 10000,
      nwarmup = 2000,
      thin = 10,
      chains = 1
    )
    
    
    # Extract the model result
    bSplines_model_results = Bayesian_Survival_result_Extract(
      bayesian_model_fit = bSplines_model,
      model_type = "bSplines",
      criteria = c(
        "DesignCoefficients",
        "variableSelection",
        "Prediction_SurvivalProb"
      )
    )
    
    bSplines_model_beta[i, ] <- bSplines_model_results$Beta_bayesian_est[, "mean"]
    bSplines_model_variableSelection[i, ] <- bSplines_model_results$variableSelection
    
    
    bSplines_model_results2 = Bayesian_Survival_result_Extract(
      bayesian_model_fit = bSplines_model2,
      model_type = "bSplines",
      criteria = c(
        "DesignCoefficients",
        "variableSelection",
        "Prediction_SurvivalProb"
      )
    )
    
    bSplines_model_beta2[i, ] <- bSplines_model_results2$Beta_bayesian_est[, "mean"]
    bSplines_model_variableSelection2[i, ] <- bSplines_model_results2$variableSelection
    
    
    cox_beta[i,] <- as.vector(cox_regression_result$coefficients[, "coef"])
    cox_variableSelection[i,] <- as.vector((cox_regression_result$coefficients[, "Pr(>|z|)"] * p) < 0.05)
    
    cox_beta2[i,] <- as.vector(cox_regression_result2$coefficients[, "coef"])
    cox_variableSelection2[i,] <- as.vector((cox_regression_result2$coefficients[, "Pr(>|z|)"] * p ) < 0.05)
    
    PL_results = Bayesian_Survival_result_Extract(
    bayesian_model_fit = PL_model,
    model_type = "none",
    criteria = c(
      "DesignCoefficients",
      "variableSelection",
      "Prediction_SurvivalProb"
    )
  )
    PL_beta[i, ] <- PL_results$Beta_bayesian_est[, "mean"]
    PL_variableSelection[i, ] <- PL_results$variableSelection
    
    PL_results2 = Bayesian_Survival_result_Extract(
    bayesian_model_fit = PL_model2,
    model_type = "none",
    criteria = c(
      "DesignCoefficients",
      "variableSelection",
      "Prediction_SurvivalProb"
    )
  )
    
    PL_beta2[i, ] <- PL_results2$Beta_bayesian_est[, "mean"]
    PL_variableSelection2[i, ] <- PL_results2$variableSelection
    
    
    ###---------------------------------------------------------
    ###-------------for simplified dataset----------------------
    ###---------------------------------------------------------
    #-----------MODEL 2.1: bSpline model----------
    Data_bSplines_Simple <- stan_data_Constructer_BSpline(
      training_dataset = training_dataset_Simple,
      testing_dataset = NULL,
      obs_window = 3415,
      log_lik_saving = FALSE,
      havingInt = TRUE
    )
    bSplines_model_Simple <-
      Bayesian_Survival_model(
        stan_data = Data_bSplines_Simple,
        baseline_modelling = "bSplines",
        shrinkage = TRUE,
        withPrediction = FALSE,
        havingInt = TRUE,
        niter = 10000,
        nwarmup = 2000,
        thin = 10,
        chains = 1
      )
    
    Data_bSplines2_Simple <- stan_data_Constructer_BSpline(
      training_dataset = training_dataset2_Simple,
      testing_dataset = NULL,
      obs_window = 3415,
      log_lik_saving = FALSE,
      havingInt = TRUE
    )
    bSplines_model2_Simple <-
      Bayesian_Survival_model(
        stan_data = Data_bSplines2_Simple,
        baseline_modelling = "bSplines",
        shrinkage = TRUE,
        withPrediction = FALSE,
        havingInt = TRUE,
        niter = 10000,
        nwarmup = 2000,
        thin = 10,
        chains = 1
      )
    
    
    #-----------MODEL 1.2: Cox regression ----------
    cox_regression_Simple <- coxph(Surv(as.numeric(obstime), status) ~ ., data = training_dataset_Simple)
    cox_regression_result_Simple <- summary(cox_regression_Simple)
    
    cox_regression2_Simple <- coxph(Surv(as.numeric(obstime), status) ~ ., data = training_dataset2_Simple)
    cox_regression_result2_Simple <- summary(cox_regression2_Simple)
   
    
    #-----------MODEL 1.3: PL model----------
    Data_PL_Simple <- stan_data_Constructer_PL(
      training_dataset = training_dataset_Simple,
      testing_dataset = NULL,
      havingInt = TRUE
    )
    
    PL_model_Simple <- Bayesian_Survival_model(
      stan_data = Data_PL_Simple,
      baseline_modelling = "none",
      shrinkage = TRUE,
      withPrediction = FALSE,
      havingInt = TRUE,
      niter = 10000,
      nwarmup = 2000,
      thin = 10,
      chains = 1
    )
    
    Data_PL2_Simple <- stan_data_Constructer_PL(
      training_dataset = training_dataset2_Simple,
      testing_dataset = NULL,
      havingInt = TRUE
    )
    
    PL_model2_Simple <- Bayesian_Survival_model(
      stan_data = Data_PL2_Simple,
      baseline_modelling = "none",
      shrinkage = TRUE,
      withPrediction = FALSE,
      havingInt = TRUE,
      niter = 10000,
      nwarmup = 2000,
      thin = 10,
      chains = 1
    )
    
    
    # Extract the model result
    bSplines_model_results_Simple = Bayesian_Survival_result_Extract(
      bayesian_model_fit = bSplines_model_Simple,
      model_type = "bSplines",
      criteria = c(
        "DesignCoefficients",
        "variableSelection",
        "Prediction_SurvivalProb"
      )
    )
    
    bSplines_model_beta_Simple[i, ] <- bSplines_model_results_Simple$Beta_bayesian_est[, "mean"]
    bSplines_model_variableSelection_Simple[i, ] <- bSplines_model_results_Simple$variableSelection
    
    
    bSplines_model_results2_Simple = Bayesian_Survival_result_Extract(
      bayesian_model_fit = bSplines_model2_Simple,
      model_type = "bSplines",
      criteria = c(
        "DesignCoefficients",
        "variableSelection",
        "Prediction_SurvivalProb"
      )
    )
    
    bSplines_model_beta2_Simple[i, ] <- bSplines_model_results2_Simple$Beta_bayesian_est[, "mean"]
    bSplines_model_variableSelection2_Simple[i, ] <- bSplines_model_results2_Simple$variableSelection
    
    
    cox_beta_Simple[i,] <- as.vector(cox_regression_result_Simple$coefficients[, "coef"])
    cox_variableSelection_Simple[i,] <- as.vector((cox_regression_result_Simple$coefficients[, "Pr(>|z|)"] * p1) < 0.05)
    
    cox_beta2_Simple[i,] <- as.vector(cox_regression_result2_Simple$coefficients[, "coef"])
    cox_variableSelection2_Simple[i,] <- as.vector((cox_regression_result2_Simple$coefficients[, "Pr(>|z|)"] * p1) < 0.05)
    
    PL_results_Simple = Bayesian_Survival_result_Extract(
    bayesian_model_fit = PL_model_Simple,
    model_type = "none",
    criteria = c(
      "DesignCoefficients",
      "variableSelection",
      "Prediction_SurvivalProb"
    )
  )
    PL_beta_Simple[i, ] <- PL_results_Simple$Beta_bayesian_est[, "mean"]
    PL_variableSelection_Simple[i, ] <- PL_results_Simple$variableSelection
    
    PL_results2_Simple = Bayesian_Survival_result_Extract(
    bayesian_model_fit = PL_model2_Simple,
    model_type = "none",
    criteria = c(
      "DesignCoefficients",
      "variableSelection",
      "Prediction_SurvivalProb"
    )
  )
    
    PL_beta2_Simple[i, ] <- PL_results2_Simple$Beta_bayesian_est[, "mean"]
    PL_variableSelection2_Simple[i, ] <- PL_results2_Simple$variableSelection
  }
  
  # Store results for this repetition
  bSplines_beta_list[[r]] <- bSplines_model_beta
  bSplines_varSel_list[[r]] <- bSplines_model_variableSelection
  PL_beta_list[[r]] <- PL_beta
  PL_varSel_list[[r]] <- PL_variableSelection
  cox_beta_list[[r]] <- cox_beta
  cox_varSel_list[[r]] <- cox_variableSelection
  
  bSplines_beta_list2[[r]] <- bSplines_model_beta2
  bSplines_varSel_list2[[r]] <- bSplines_model_variableSelection2
  PL_beta_list2[[r]] <- PL_beta2
  PL_varSel_list2[[r]] <- PL_variableSelection2
  cox_beta_list2[[r]] <- cox_beta2
  cox_varSel_list2[[r]] <- cox_variableSelection2
  
  
  # Store results for this repetition --- simplified dataset
  bSplines_beta_list_Simple[[r]] <- bSplines_model_beta_Simple
  bSplines_varSel_list_Simple[[r]] <- bSplines_model_variableSelection_Simple
  PL_beta_list_Simple[[r]] <- PL_beta_Simple
  PL_varSel_list_Simple[[r]] <- PL_variableSelection_Simple
  cox_beta_list_Simple[[r]] <- cox_beta_Simple
  cox_varSel_list_Simple[[r]] <- cox_variableSelection_Simple
  
  bSplines_beta_list2_Simple[[r]] <- bSplines_model_beta2_Simple
  bSplines_varSel_list2_Simple[[r]] <- bSplines_model_variableSelection2_Simple
  PL_beta_list2_Simple[[r]] <- PL_beta2_Simple
  PL_varSel_list2_Simple[[r]] <- PL_variableSelection2_Simple
  cox_beta_list2_Simple[[r]] <- cox_beta2_Simple
  cox_varSel_list2_Simple[[r]] <- cox_variableSelection2_Simple
}

save.image(file = "./Data/03_results_combined_Step5_includSimplifiedData.RData")
```


```{r, echo=TRUE}
# Visualize the model results
par(mfrow = c(3, 2))
plot(bSplines_model_subset_beta[1,], type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_subset_variableSelection[1,])) {
  if (bSplines_model_subset_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_subset_beta[1,], type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")


plot(bSplines_model_subset_beta[2,], type = "o", col = "blue", xlab = "", ylab = "Beta", main = "Beta estimation", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(bSplines_model_subset_variableSelection[2,])) {
  if (bSplines_model_subset_variableSelection[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}
lines(bSplines_model_subset_beta[2,], type = "o", col = "blue", pch = 16)
#axis(1, at = 1:91, labels = "", las = 2, cex.axis = 0.7)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")



plot(PL_subset_beta[1,], type = "o", col = "darkgreen", xlab = "", ylab = "Beta", main = "", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(PL_subset_variableSelection[1,])) {
  if (PL_subset_variableSelection[1,]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(PL_subset_beta[1,], type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")

plot(PL_subset_beta[2,], type = "o", col = "darkgreen", xlab = "", ylab = "Beta", main = "", pch = 16, xaxt = "n")
# Add background rectangles
for (i in 1:length(PL_subset_variableSelection[2,])) {
  if (PL_subset_variableSelection[2,]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightgreen", border = NA)
  }
}
lines(PL_subset_beta[2,], type = "o", col = "darkgreen", pch = 16)
axis(1, at = 1:91, labels = names(strafied_Data_DBD_int)[1:91], las = 2, cex.axis = 0.7)
abline(a = 0, b =0, col = "red")
```


