---
title: "06_real_data_visualization"
author: "Yufang"
date: "2025-05-28"
output: pdf_document
---


```{r, echo = FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#G:/MasterThesis/Code/"
source("./function_file/Functions.R")
source("./function_file/stan_constructor.R")

install_and_load <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {
      install.packages(pkg, dependencies = TRUE)
    }
    library(pkg, character.only = TRUE) }
  
}

# List of required packages
required_packages <- c("rstan", "MASS", "rstantools", "coda", "readr", "survival", "splines2", "dplyr", "simsurv", "Hmisc", "caret", "corrplot","ggplot2")
# Install and/or load packages
install_and_load(required_packages)
```
Make sure the existence of interaction effects
```{r, echo=TRUE}
cross_validated_likelihood <- function(D, ){
  likelihood_beta_hat_min_ls <- rep(NA, nrow(D))
  # SD <- D[order(-D$obstime, -D$status), ] # observed time points (non-strict decreasing), first sort with obstime, then status
  # t_points = D[, "obstime"]
  likelihood_beta <- 
  for (i in 1:nrow(D)){
    likelihood_beta_hat_min_l <- 
    likelihood_beta_hat_min_ls[i] <- likelihood_beta - likelihood_beta_hat_min_l
  }
  
  cvl = mean(likelihood_beta_hat_min_ls)
  return(cvl)
}
```

For DBD
```{r, echo=TRUE}
load("./Data/03_results_DBD.RData")
# Selected by bSpline model
names(strafied_Data_DBD_int)[!names(strafied_Data_DBD_int) %in% c("id", "status", "obstime")][variableSelection_DBD]

# Selected by PH model
names(strafied_Data_DBD_int)[!names(strafied_Data_DBD_int) %in% c("id", "status", "obstime")][variableSelection_DBD_PH]

cor(mean_beta_DBD, mean_beta_DBD_PH)
```

For DBD_2
```{r, echo=TRUE}
load("./Data/03_results_DBD_2.RData")
# Selected by bSpline model
names(strafied_Data_DBD_int)[!names(strafied_Data_DBD_int) %in% c("id", "status", "obstime")][variableSelection_DBD]

# Selected by PH model
names(strafied_Data_DBD_int)[!names(strafied_Data_DBD_int) %in% c("id", "status", "obstime")][variableSelection_DBD_PH]

cor(mean_beta_DBD, mean_beta_DBD_PH)
```

For DCD
```{r, echo=TRUE}
load("./Data/03_results_DCD.RData")
# Selected by bSpline model
names(strafied_Data_DCD_int)[!names(strafied_Data_DCD_int) %in% c("id", "status", "obstime")][variableSelection_DCD]

# Selected by PH model
names(strafied_Data_DCD_int)[!names(strafied_Data_DCD_int) %in% c("id", "status", "obstime")][variableSelection_DBD_PH]

cor(mean_beta_DCD, mean_beta_DCD_PH)
```
For DCD_2
```{r, echo=TRUE}
load("./Data/03_results_DCD_2.RData")
# Selected by bSpline model
names(strafied_Data_DCD_int)[!names(strafied_Data_DCD_int) %in% c("id", "status", "obstime")][variableSelection_DCD]

# Selected by PH model
names(strafied_Data_DCD_int)[!names(strafied_Data_DCD_int) %in% c("id", "status", "obstime")][variableSelection_DBD_PH]

cor(mean_beta_DCD, mean_beta_DCD_PH)
```