---
title: "07_cross_validated_loglikelihood"
author: "Yufang Wang"
date: "2025-06-03"
output: html_document
---

```{r, echo=TRUE, message=FALSE, warning=FALSE}
rm(list = ls())
setwd("C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#G:/MasterThesis/Code/"

install_and_load <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {
      install.packages(pkg, dependencies = TRUE)
    }
    library(pkg, character.only = TRUE) }
  
}

# List of required packages
required_packages <- c("rstan", "MASS", "rstantools", "coda", "readr", "survival", "splines2", "dplyr", "simsurv", "Hmisc", "caret", "foreach", "loo")
# Install and/or load packages
install_and_load(required_packages)

source("./function_file/Functions.R")
source("./function_file/stan_constructor.R")
```


# Step 2: Organize the real-world data
```{r, echo=TRUE}
real_df <- readRDS("./Data/imputed_NOTR_DGF.rds")
sum(!complete.cases(real_df))
mean(real_df$status == "graftloss")
mean(real_df$status == "alive")
mean(real_df$status == "death")

real_df <- real_df[, !names(real_df) %in% "ID"]

# get a general idea about the dataset
for (i in 1:ncol(real_df)) { 
  if (is.factor(real_df[[i]])) {
    print(names(real_df)[i])
    print(length(unique(real_df[[i]])))
    }
}
factorName <- sapply(real_df, is.factor)
factorName["status"] <- FALSE

real_df <- real_df[, !(names(real_df) %in% "InitialOnmachineindicator")]
real_df$Donorcauseofdeath_group <- ifelse(real_df$Donorcauseofdeath_group == "Cardiac", "Cardiac", "Others")
real_df$InitialPrimaryDiseaseET_regroup <- ifelse(real_df$InitialPrimaryDiseaseET_regroup == "Diabetes Mellitus", "Diabetes", "Others")

strafied_Data_DBD <- subset(subset(real_df, real_df$TypecadavericDBDDCD == "DBD"), select = -c(TypecadavericDBDDCD, Warm_ischaemic_period_1))

strafied_Data_DCD <- subset(subset(real_df, real_df$TypecadavericDBDDCD == "DCD"), select = -c(TypecadavericDBDDCD))
```

# reorganized the dataset with including interaction effects
```{r, echo=TRUE}
includingInter <- function(dataframe_) {
  #sum-coded all factor variables
  factor_var <- sapply(dataframe_, is.factor)
  for (var in names(dataframe_)[factor_var]) {
    if (var != "status") {
      contrasts(dataframe_[[var]]) <- contr.sum(levels(dataframe_[[var]]))
    }
  }
  numeric_var <- sapply(dataframe_, is.numeric)
  for (var in names(dataframe_)[numeric_var]){
    if (var != "time"){
      dataframe_[[var]] <- (dataframe_[[var]] - mean(dataframe_[[var]], na.rm = TRUE)) / sd(dataframe_[[var]], na.rm = TRUE)
    }
    
  }
  
  # print(colnames(dataframe_)[numeric_var])
  
  # build up interaction effect
  predictors <- subset(dataframe_, select = -c(status, time))
  
  interaction_formula <- as.formula(paste("~ (", paste(colnames(predictors), collapse = " + "), ")^2"))
  interaction_matrix <- model.matrix(interaction_formula, data = dataframe_)
  
  interaction_df <- as.data.frame(interaction_matrix)
  interaction_df <- interaction_df[, -1]
  
# Exclude interactions involving categorical variables
  all_terms <- colnames(interaction_df)
  interaction_terms <- all_terms[grepl(":", all_terms)]
  # print(interaction_terms)
  factor_vars <- c("Recipientsex", "Donorsex", "Smoking", "InitialOnmachineindicator", "status", "InitialPrimaryDiseaseET_regroup", "Donorcauseofdeath_group")#colnames(dataframe_)[factor_var]
  # print(factor_vars)
  
  exclude_terms <- sapply(interaction_terms, function(term) {
    terms_ <- unlist(strsplit(term, ":"))
    Con1 <- any(agrepl(terms_[1], factor_vars))
    Con2 <- any(agrepl(terms_[2], factor_vars))
    if ((Con2 | Con1)){
      Con1 = agrepl(terms_[1], "InitialPrimaryDiseaseET_regroup")
      Con2 = agrepl(terms_[2], "InitialPrimaryDiseaseET_regroup")

      return(any(Con1, Con2))
      # print(terms_[2])
      # print(Con2)
    }
    # print(term)
    # print(all(Con1, Con2))
    return(all(Con1, Con2))
  })
  
  # print(exclude_terms)
  exclude_columns <- interaction_terms[exclude_terms]
  selected_columns <- setdiff(all_terms, exclude_columns)
  interaction_df <- subset(interaction_df, select = selected_columns)
  interaction_df$id = 1:nrow(dataframe_)#dataframe_$ID
  interaction_df$status = ifelse(dataframe_$status == "graftloss", 1, 0)
  interaction_df$obstime = dataframe_$time


  # print(interaction_terms[exclude_terms])

  
  return(interaction_df)
}
```

# For DBD
## cross-validated log likelihood
```{r, echo=TRUE}
cross_validated_likelihood <- function(model_fit_bSpline, nObs) {
  cvl_s = rep(NA, nObs)
  log_lik_matrix <- extract_log_lik(model_fit_bSpline,
                                    parameter_name = "log_lik",
                                    merge_chains = TRUE) # S*N
  log_lik <- max(apply(log_lik_matrix, 1, sum))
  
  for (i in 1:ncol(log_lik_matrix)) {
    cvl_s[i] <- max(apply(log_lik_matrix[, -i], 1, sum))
  }
  return(sum(cvl_s))
}


```

