---
title: "EDA_Thesis"
author: "Yufang Wang"
date: "2025-03-04"
output: pdf_document
---
```{r, echo=TRUE}
rm(list = ls())
library(dplyr)
df_using <- readRDS("./Data/preprocessed_NOTR_DGF.rds")
```

###  summarize of data 2: to get the variable description
```{r, echo=TRUE}
# Create a correlation matrix
cor_matrix <- cor(df_using[, sapply(df_using, is.numeric)])
library(corrplot)
# Plot the correlation matrix
corrplot(cor_matrix, method = "color", type = "upper", 
         tl.col = "black", tl.srt = 45, 
         addCoef.col = "black", number.cex = 0.7)

results2 <- data.frame(
  Variable = character(),
  mean_val = numeric(),
  medium_val = numeric(),
  sd_val = numeric()
)

library(ggplot2)
# Function to create bar plots for factor columns
create_barplot <- function(df, var) {
   ggplot(df, aes_string(x = var, fill = var)) +
    geom_bar() +
    labs(title = paste("Bar Plot of", var), x = var, y = "Proportion") +
    theme_minimal() +
    theme(legend.position = "bottom")
}

# Loop through each column in the data frame
for (var in colnames(df_using)) {
  if (is.numeric(df_using[[var]])){
    results2 <- rbind(results2, data.frame(
      Variable = var,
      mean_val = mean(df_using[[var]]),
      median_val = median(df_using[[var]]),
      sd_val =  sd(df_using[[var]])
    ))
  } else if (!is.numeric(df_using[[var]]) & !inherits(df_using[[var]], "Date")) {
    print(create_barplot(df_using, var))
  }
}

# Print the results data frame
print(results2)
```

## check fothe missing data of numeric variables
```{r, echo=TRUE}
results <- data.frame(
  Variable = character(),
  LengthUniqueValues = integer(),
  MissingObs = integer(),
  UniqueValues = character()
)

# Loop through each column in the data frame
for (var in colnames(df_using)) {
  if (!is.numeric(df_using[[var]]) & !inherits(df_using[[var]], "Date")) {
    # Convert unique values to a single string
    unique_values_str <- paste(unique(df_using[[var]]), collapse = ", ")
    
    # Add the variable name, unique values, and number of unique values to the results data frame
    results <- rbind(results, data.frame(
      Variable = var,
      LengthUniqueValues = length(unique(df_using[[var]])),
      MissingObs = sum(is.na(df_using[[var]])),
      UniqueValues = unique_values_str
    ))
  }
  
  else{
     results <- rbind(results, data.frame(
      Variable = var,
      LengthUniqueValues = length(unique(df_using[[var]])),
      MissingObs = sum(is.na(df_using[[var]])),
      UniqueValues = unique_values_str
    ))
  }
}

# Print the results data frame
print(results)
```



## recensoring data because of not accounting for completing risks: only focusing on graft loss
```{r, echo=TRUE}
library(survival)
df_using$status2 = ifelse(df_using$status == "graftloss", 1, 0)
sf = survfit(Surv(time,status2) ~ 1, data=df_using)
plot(sf$time, 1 - sf$surv, xlab = "Days in kidney transplation",
     ylab = "Cumulative distribution function", main = "The chance to experience graftloss before time t")
```
## Exploring the liner/non-linear relationship between the event of "graftloss" and other variables one-by-one

```{r, echo=TRUE}
create_EDA <- function(df, var){
  if (is.numeric(df[[var]])){
    print(var)
    model <- coxph(Surv(time, status2) ~ pspline(df[[var]], df = 4), data = df)
    termplot(model, term = 1, se = TRUE, transform.x = TRUE, partial.resid = TRUE,
             col.term = "blue", col.se = "red", xlabs = paste(var), 
             ylabs = paste("Parietal for Pspline (", var, ")"),
             main = paste("Effect of transformed", var, "on Hazard Function"))
  } else if (is.factor(df[[var]])){
    print(var)
    model1 <- coxph(Surv(time, status2) ~ df[[var]], data = df)
    print(summary(model1))
  }
}

for (variable in colnames(df_using)){
  create_EDA(df_using, var = variable)
}
```
