---
title: "Generate_sim_data"
author: "Yufang Wang"
date: "2025-03-18"
output: pdf_document
---

# Step 1: Set up the environment
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#C:/Users/Alisa_Wang/Desktop/MasterThesis/Code/")#G:/MasterThesis/Code/"
source("./function_file/Functions.R")

install_and_load <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {
      install.packages(pkg, dependencies = TRUE)
    }
    library(pkg, character.only = TRUE) }
  
}

# List of required packages
required_packages <- c("rstan", "MASS", "rstantools", "coda", "readr", "survival", "splines2", "dplyr", "simsurv", "Hmisc", "caret")
# Install and/or load packages
install_and_load(required_packages)
```


# Step 2: Generate simulated data
```{r, echo=TRUE}
set.seed(123)
n_samples <- 300
n_features <- 10 

# function for one simulation
simulation_bayint_survival <- function(criteria = c("DesignCoefficients", "baseline", "variableSelection"), withPrediction = FALSE){
  output = list()
  
  simulated_data <- DataGenerator(n_samples = n_samples, n_features = 10)
  dataset <- simulated_data$dataset
  Beta <- simulated_data$Beta
  output$Beta_true = Beta
  
  #constructor data for the model
  if (withPrediction) {
    stan_data_exponential <- stan_data_Constructer(
      training_dataset = dataset,
      withPrediction = withPrediction,
      testing_dataset = tail(dataset, 100),
      baseline_modelling = "exponential",
      obs_window = 5
    )
    stan_data_weibull <- stan_data_Constructer(
      training_dataset = dataset,
      withPrediction = withPrediction,
      testing_dataset = tail(dataset, 100),
      baseline_modelling = "weibull",
      obs_window = 5
    )
    stan_data_bSplines <- stan_data_Constructer(
      training_dataset = dataset,
      withPrediction = withPrediction,
      testing_dataset = tail(dataset, 100),
      baseline_modelling = "bSplines",
      obs_window = 5
    )
  }  else {
    stan_data_exponential <- stan_data_Constructer(
      training_dataset = dataset,
      withPrediction = withPrediction,
      baseline_modelling = "exponential",
      obs_window = 5
    )
    stan_data_weibull <- stan_data_Constructer(
      training_dataset = dataset,
      withPrediction = withPrediction,
      baseline_modelling = "weibull",
      obs_window = 5
    )
    stan_data_bSplines <- stan_data_Constructer(
      training_dataset = dataset,
      baseline_modelling = "bSplines",
      obs_window = 5
    )
  }
    
  #fit model
  model_fit_exponential <-  Bayesian_Survival_model(stan_data = stan_data_exponential, baseline_assumption = "exponential")
  model_fit_weibull <- Bayesian_Survival_model(stan_data = stan_data_weibull, baseline_assumption = "weibull")
  model_fit_bSplines <- Bayesian_Survival_model(stan_data = stan_data_bSplines, baseline_assumption = "bSplines")

  #extract the info from the bayesian model fit
  model_result_exponential <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_exponential, model_type = "exponential", criteria = criteria)
  model_result_weibull <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_weibull,  model_type = "weibull", criteria = criteria)
  model_result_bSplines <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit_bSplines, model_type = "bSplines", criteria = criteria)
  
  #---------cofficients for X----------
  if ("DesignCoefficients" %in% criteria){
    output$Beta_est_exponential = model_result_exponential$Beta_bayesian_est[, "mean"]
    output$Beta_est_weibull = model_result_weibull$Beta_bayesian_est[, "mean"]
    output$Beta_est_bSplines = model_result_bSplines$Beta_bayesian_est[, "mean"]
  }
  
  #----------baseline hazard----------
  # Transfer the param into baseline 
  # hazard function regarding t
  #-----------------------------------
  
  if ("baseline" %in% criteria) {
    time_vec <-
      sort(dataset[dataset$status == 1, ]$obstime) # obs_window = 5
    output$baseline_exponential <-
      rep(model_result_exponential$baselinePara, length(time_vec))
    
    weibull_lambda <- model_result_weibull$baselinePara[1]
    weibull_shape <- model_result_weibull$baselinePara[2]
    output$baseline_weibull <-
      weibull_shape * weibull_lambda * (time_vec ** (weibull_shape - 1))
    
    output$baseline_bSplines <-
      exp(
        as.matrix(stan_data_bSplines$basis) %*% as.matrix(model_result_bSplines$baselinePara[, "mean"])
      )
  }
  
  
  if ("variableSelection" %in% criteria) {
    output$variableSelection_exponential <-
      model_result_exponential$variableSelection
    output$variableSelection_weibull <-
      model_result_weibull$variableSelection
    output$variableSelection_bSplines <-
      model_result_bSplines$variableSelection
  }
  
  # if ("Prediction_SurvivalProb" %in% criteria) {
  #   output$sp_exponential = model_result_exponential$sp
  #   output$sp_weibull = model_result_weibull$sp
  #   output$sp_bSplines = model_result_bSplines$sp
  # }
  return(output)
}

simulated_results <- replicate(1, simulation_bayint_survival(), simplify = "array")
# save.image(file = "./Data/sim_50_para_int.RData")
```

```{r, echo=TRUE}
load(file = "./Data/sim_50_para_int.RData")
replicate_times = 50
MSEs_exponential = matrix(nrow = replicate_times, ncol = 55)
MSEs_weibull = matrix(nrow = replicate_times, ncol = 55)
MSEs_bSplines = matrix(nrow = replicate_times, ncol = 55)

FDR_exponential = rep(NA, replicate_times)
FDR_weibull = rep(NA, replicate_times)
FDR_bSplines = rep(NA, replicate_times)

for (i in 1:replicate_times){
  Beta_true <- simulated_results[,i]$Beta_true
  Beta_est_exponential <- simulated_results[,i]$Beta_est_exponential
  Beta_est_weibull <- simulated_results[,i]$Beta_est_weibull
  Beta_est_bSplines <-  simulated_results[,i]$Beta_est_bSplines
  
  MSEs_exponential[i, ] <- (Beta_est_exponential - Beta_true)**2
  MSEs_weibull[i, ] <- (Beta_est_weibull - Beta_true)**2
  MSEs_bSplines[i, ] <- (Beta_est_bSplines - Beta_true)**2
  
  
  variableSelection_reference <- ifelse(simulated_results[,i]$Beta_true != 0, TRUE, FALSE)
  Selection_exponential <- simulated_results[,i]$variableSelection_exponential 
  Selection_weibull <- simulated_results[,i]$variableSelection_weibull
  Selection_bSplines <- simulated_results[,i]$variableSelection_bSplines
  
  FDR_exponential[i] <- sum(Selection_exponential & !variableSelection_reference) / sum(Selection_exponential)
  FDR_weibull[i] <- sum(Selection_weibull & !variableSelection_reference) / sum(Selection_weibull)
  FDR_bSplines[i] <- sum(Selection_bSplines & !variableSelection_reference) / sum(Selection_bSplines)
  
}

mean_MSEs_exponential <- apply(MSEs_exponential, 2, mean)
mean_MSEs_weibull <- apply(MSEs_weibull, 2, mean)
mean_MSEs_bSplines <- apply(MSEs_bSplines, 2, mean)

# visualized result
fill_vector = (simulated_results[, 1]$Beta_true != 0)

plot(mean_MSEs_exponential, type = "o", col = "blue", xlab = "estimated Betas", ylab = "MSE", ylim = c(0, 0.3), main = "MSE for Beta estimation", pch = 16)

# Add background rectangles
for (i in 1:length(mean_MSEs_exponential)) {
  if (fill_vector[i]) {
    rect(i - 0.5, par("usr")[3], i + 0.5, par("usr")[4], col = "lightblue", border = NA)
  }
}

lines(mean_MSEs_weibull, type = "o", col = "green", pch = 16)
lines(mean_MSEs_bSplines, type = "o", col = "orange", pch = 16)
lines(mean_MSEs_exponential, type = "o", col = "blue", pch = 16)
abline(v = 10, col = "red", lty = 2)
# Add legend
legend("topright", legend = c("Exponential", "Weibull", "B-Splines"), col = c("blue", "green", "orange"), pch = 16, lty = 1)

# Create side-by-side boxplots for FDR
FDR_list = list(FDR_exponential = FDR_exponential, FDR_weibull = FDR_weibull, FDR_bSplines = FDR_bSplines)
boxplot(FDR_list, names = c("FDR_exponential", "FDR_weibull", "FDR_bSplines"), col = c("blue", "green", "orange"), main = "Side-by-Side Boxplots", xlab = "", ylab = "FDR")

```

# Step 3: visualize the estimated basline hazard
```{r, echo=TRUE}
for (i in 1:replicate_times) {
  baseline_exponential <- simulated_results[, i]$baseline_exponential
  baseline_weibull <- simulated_results[, i]$baseline_weibull
  baseline_bSplines <- simulated_results[, i]$baseline_bSplines
  
  plot(baseline_weibull, col = "green", type = "l", pch = 16, lty = 1, lwd = 2)
  lines(baseline_exponential, col = "blue", pch = 16, lty = 1, lwd = 2)
  lines(baseline_bSplines, col = "orange", pch = 16, lty = 1, lwd = 2)
  # Add legend
  legend(
    "topleft",
    legend = c("Exponential", "Weibull", "B-Splines"),
    col = c("blue", "green", "orange"),
    pch = 16,
    lty = 1
  )
}

```

# Step 4: use cross validation for prediction.
```{r, echo=TRUE}
cross_validation <- function(whole_dataset, baseline_modelling = "weibull", num_folds = 5){
  # create the cross-validation folds
  folds <- createFolds(whole_dataset$status, k = num_folds, list = TRUE, returnTrain = FALSE)
  cross_val_metric <- list()
  rMSE_s = matrix(nrow = 5, ncol = 55); Brier_scores =  rep(NA, 5); C_indices =  rep(NA, 5); FDR_vals =  rep(NA, 5)
  for (i in 1:num_folds){
    fold_indices <- folds[[i]]
    training_data = whole_dataset[-fold_indices, ]
    testing_data = whole_dataset[fold_indices, ]
    stan_data <- stan_data_Constructer(training_dataset = training_data, testing_dataset = testing_data, baseline_modelling = baseline_modelling, obs_window = 5)
    model_fit <- Bayesian_Survival_model(stan_data = stan_data, baseline_assumption = baseline_modelling)
    
    #extract the info from the bayesian model fit
    model_result <- Bayesian_Survival_result_Extract(bayesian_model_fit = model_fit)
    
    ComparsionValues <- list(
      Beta_reference = c(beta, rep(0, 45)),
      test_t = testing_data$obstime,
      test_status = testing_data$status,
      Selection_reference = c(rep(TRUE, 10), rep(FALSE, 45))
      )
    model_metric <- Model_performance_eval(model_result = model_result, ComparsionValues)
    rMSE_s[i, ] <- model_metric$rMSE
    Brier_scores[i] <- model_metric$Brier_score
    C_indices[i] <- model_metric$C_index
    FDR_vals[i] <- model_metric$FDR
  }
  cross_val_metric$rMSE_s <- rMSE_s
  cross_val_metric$Brier_scores <- Brier_scores
  cross_val_metric$C_indices <- C_indices
  cross_val_metric$FDR_vals <- FDR_vals
  
  return(cross_val_metric)
}

cross_val_metric <- cross_validation(whole_dataset = sim_data, baseline_modelling = "bSplines") # exponential, weibull, bSplines

# Step 3: visualize the model metric results
metric_visualization(cross_val_metric)
```

